blocks = [
  # Dungeons Format:
  #   0: Block ID
  #   1: Block Data
  #   2: Block Data Mask

  # Java Format:
  #   0: Block ID
  #   1: Block Properties

  { 'dungeons': [ 0x00 ], 'java': [ 'minecraft:air' ] },
  { 'dungeons': [ 0x01, 0b0000 ], 'java': [ 'minecraft:stone' ] },
  { 'dungeons': [ 0x01, 0b0001 ], 'java': [ 'minecraft:granite' ] },
  { 'dungeons': [ 0x01, 0b0010 ], 'java': [ 'minecraft:polished_granite' ] },
  { 'dungeons': [ 0x01, 0b0011 ], 'java': [ 'minecraft:diorite' ] },
  { 'dungeons': [ 0x01, 0b0100 ], 'java': [ 'minecraft:polished_diorite' ] },
  { 'dungeons': [ 0x01, 0b0101 ], 'java': [ 'minecraft:andesite' ] },
  { 'dungeons': [ 0x01, 0b0110 ], 'java': [ 'minecraft:polished_andesite' ] },
  { 'dungeons': [ 0x01, 0b0111 ], 'java': [ 'minecraft:blackstone' ] }, # stonefloor1
  { 'dungeons': [ 0x01, 0b1000 ], 'java': [ 'minecraft:chiseled_polished_blackstone' ] }, # stonefloor2
  { 'dungeons': [ 0x01, 0b1001 ], 'java': [ 'minecraft:polished_blackstone' ] }, # stonefloor3
  { 'dungeons': [ 0x01, 0b1010 ], 'java': [ 'minecraft:polished_blackstone_bricks' ] }, # stonefloor4
  { 'dungeons': [ 0x01, 0b1011 ], 'java': [ 'minecraft:gilded_blackstone' ] }, # stonefloor5
  { 'dungeons': [ 0x01, 0b1100 ], 'java': [ 'minecraft:cracked_polished_blackstone_bricks' ] }, # stonefloor6
  { 'dungeons': [ 0x01, 0b1101 ], 'java': [ 'minecraft:lodestone' ] }, # stonefloor7
  { 'dungeons': [ 0x01, 0b1110 ], 'java': [ 'minecraft:ancient_debris' ] }, # stonefloor8
  { 'dungeons': [ 0x01, 0b1111 ], 'java': [ 'minecraft:infested_chiseled_stone_bricks' ] }, # stonefloor9
  { 'dungeons': [ 0x02, 0b0000 ], 'java': [ 'minecraft:grass_block' ] },
  { 'dungeons': [ 0x03, 0b0000 ], 'java': [ 'minecraft:dirt' ] },
  { 'dungeons': [ 0x03, 0b0001 ], 'java': [ 'minecraft:coarse_dirt' ] },
  { 'dungeons': [ 0x04, 0b0000 ], 'java': [ 'minecraft:cobblestone' ] },
  { 'dungeons': [ 0x05, 0b0000 ], 'java': [ 'minecraft:oak_planks' ] },
  { 'dungeons': [ 0x05, 0b0001 ], 'java': [ 'minecraft:spruce_planks' ] },
  { 'dungeons': [ 0x05, 0b0010 ], 'java': [ 'minecraft:birch_planks' ] },
  { 'dungeons': [ 0x05, 0b0011 ], 'java': [ 'minecraft:jungle_planks' ] },
  { 'dungeons': [ 0x05, 0b0100 ], 'java': [ 'minecraft:acacia_planks' ] },
  { 'dungeons': [ 0x05, 0b0101 ], 'java': [ 'minecraft:dark_oak_planks' ] },
  { 'dungeons': [ 0x06, 0b0000 ], 'java': [ 'minecraft:oak_sapling', { 'stage': '0' } ] },
  { 'dungeons': [ 0x06, 0b0001 ], 'java': [ 'minecraft:spruce_sapling', { 'stage': '0' } ] },
  { 'dungeons': [ 0x06, 0b0010 ], 'java': [ 'minecraft:birch_sapling', { 'stage': '0' } ] },
  { 'dungeons': [ 0x06, 0b0011 ], 'java': [ 'minecraft:jungle_sapling', { 'stage': '0' } ] },
  { 'dungeons': [ 0x06, 0b0100 ], 'java': [ 'minecraft:acacia_sapling', { 'stage': '0' } ] },
  { 'dungeons': [ 0x06, 0b0101 ], 'java': [ 'minecraft:dark_oak_sapling', { 'stage': '0' } ] },
  { 'dungeons': [ 0x06, 0b1000 ], 'java': [ 'minecraft:oak_sapling', { 'stage': '1' } ] },
  { 'dungeons': [ 0x06, 0b1001 ], 'java': [ 'minecraft:spruce_sapling', { 'stage': '1' } ] },
  { 'dungeons': [ 0x06, 0b1010 ], 'java': [ 'minecraft:birch_sapling', { 'stage': '1' } ] },
  { 'dungeons': [ 0x06, 0b1011 ], 'java': [ 'minecraft:jungle_sapling', { 'stage': '1' } ] },
  { 'dungeons': [ 0x06, 0b1100 ], 'java': [ 'minecraft:acacia_sapling', { 'stage': '1' } ] },
  { 'dungeons': [ 0x06, 0b1101 ], 'java': [ 'minecraft:dark_oak_sapling', { 'stage': '1' } ] },
  { 'dungeons': [ 0x07, 0b0000 ], 'java': [ 'minecraft:bedrock' ] },
  { 'dungeons': [ 0x08, 0b0000 ], 'java': [ 'minecraft:water', { 'level': '1' } ] },
  { 'dungeons': [ 0x08, 0b0001 ], 'java': [ 'minecraft:water', { 'level': '2' } ] },
  { 'dungeons': [ 0x08, 0b0010 ], 'java': [ 'minecraft:water', { 'level': '3' } ] },
  { 'dungeons': [ 0x08, 0b0011 ], 'java': [ 'minecraft:water', { 'level': '4' } ] },
  { 'dungeons': [ 0x08, 0b0100 ], 'java': [ 'minecraft:water', { 'level': '5' } ] },
  { 'dungeons': [ 0x08, 0b0101 ], 'java': [ 'minecraft:water', { 'level': '6' } ] },
  { 'dungeons': [ 0x08, 0b0110 ], 'java': [ 'minecraft:water', { 'level': '7' } ] },
  { 'dungeons': [ 0x08, 0b0111 ], 'java': [ 'minecraft:water', { 'level': '8' } ] },
  { 'dungeons': [ 0x08, 0b1000 ], 'java': [ 'minecraft:water', { 'level': '9' } ] },
  { 'dungeons': [ 0x08, 0b1001 ], 'java': [ 'minecraft:water', { 'level': '10' } ] },
  { 'dungeons': [ 0x08, 0b1010 ], 'java': [ 'minecraft:water', { 'level': '11' } ] },
  { 'dungeons': [ 0x08, 0b1011 ], 'java': [ 'minecraft:water', { 'level': '12' } ] },
  { 'dungeons': [ 0x08, 0b1100 ], 'java': [ 'minecraft:water', { 'level': '13' } ] },
  { 'dungeons': [ 0x08, 0b1101 ], 'java': [ 'minecraft:water', { 'level': '14' } ] },
  { 'dungeons': [ 0x08, 0b1110 ], 'java': [ 'minecraft:water', { 'level': '15' } ] },
  { 'dungeons': [ 0x09 ], 'java': [ 'minecraft:water', { 'level': '0' } ] },
  { 'dungeons': [ 0x0b ], 'java': [ 'minecraft:lava' ] },
  { 'dungeons': [ 0x0c, 0b0000 ], 'java': [ 'minecraft:sand' ] },
  { 'dungeons': [ 0x0c, 0b0001 ], 'java': [ 'minecraft:red_sand' ] },
  { 'dungeons': [ 0x0d, 0b0000 ], 'java': [ 'minecraft:gravel' ] },
  { 'dungeons': [ 0x0e, 0b0000 ], 'java': [ 'minecraft:gold_ore' ] },
  { 'dungeons': [ 0x0f, 0b0000 ], 'java': [ 'minecraft:iron_ore' ] },
  { 'dungeons': [ 0x10, 0b0000 ], 'java': [ 'minecraft:coal_ore' ] },
  { 'dungeons': [ 0x11, 0b0000 ], 'java': [ 'minecraft:oak_log', { 'axis': 'y' } ] },
  { 'dungeons': [ 0x11, 0b0001 ], 'java': [ 'minecraft:spruce_log', { 'axis': 'y' } ] },
  { 'dungeons': [ 0x11, 0b0010 ], 'java': [ 'minecraft:birch_log', { 'axis': 'y' } ] },
  { 'dungeons': [ 0x11, 0b0011 ], 'java': [ 'minecraft:jungle_log', { 'axis': 'y' } ] },
  { 'dungeons': [ 0x11, 0b0100 ], 'java': [ 'minecraft:oak_log', { 'axis': 'x' } ] },
  { 'dungeons': [ 0x11, 0b0101 ], 'java': [ 'minecraft:spruce_log', { 'axis': 'x' } ] },
  { 'dungeons': [ 0x11, 0b0110 ], 'java': [ 'minecraft:birch_log', { 'axis': 'x' } ] },
  { 'dungeons': [ 0x11, 0b0111 ], 'java': [ 'minecraft:jungle_log', { 'axis': 'x' } ] },
  { 'dungeons': [ 0x11, 0b1000 ], 'java': [ 'minecraft:oak_log', { 'axis': 'z' } ] },
  { 'dungeons': [ 0x11, 0b1001 ], 'java': [ 'minecraft:spruce_log', { 'axis': 'z' } ] },
  { 'dungeons': [ 0x11, 0b1010 ], 'java': [ 'minecraft:birch_log', { 'axis': 'z' } ] },
  { 'dungeons': [ 0x11, 0b1011 ], 'java': [ 'minecraft:jungle_log', { 'axis': 'z' } ] },
  { 'dungeons': [ 0x11, 0b1100 ], 'java': [ 'minecraft:oak_wood' ] },
  { 'dungeons': [ 0x11, 0b1101 ], 'java': [ 'minecraft:spruce_wood' ] },
  { 'dungeons': [ 0x11, 0b1110 ], 'java': [ 'minecraft:birch_wood' ] },
  { 'dungeons': [ 0x11, 0b1111 ], 'java': [ 'minecraft:jungle_wood' ] },
  { 'dungeons': [ 0x12, 0b0000, 0b0111 ], 'java': [ 'minecraft:oak_leaves', { 'persistent': 'false' } ] },
  { 'dungeons': [ 0x12, 0b0001, 0b0111 ], 'java': [ 'minecraft:spruce_leaves', { 'persistent': 'false' } ] },
  { 'dungeons': [ 0x12, 0b0010, 0b0111 ], 'java': [ 'minecraft:birch_leaves', { 'persistent': 'false' } ] },
  { 'dungeons': [ 0x12, 0b0011, 0b0111 ], 'java': [ 'minecraft:jungle_leaves', { 'persistent': 'false' } ] },
  { 'dungeons': [ 0x12, 0b0100, 0b0111 ], 'java': [ 'minecraft:oak_leaves', { 'persistent': 'true' } ] },
  { 'dungeons': [ 0x12, 0b0101, 0b0111 ], 'java': [ 'minecraft:spruce_leaves', { 'persistent': 'true' } ] },
  { 'dungeons': [ 0x12, 0b0110, 0b0111 ], 'java': [ 'minecraft:birch_leaves', { 'persistent': 'true' } ] },
  { 'dungeons': [ 0x12, 0b0111, 0b0111 ], 'java': [ 'minecraft:jungle_leaves', { 'persistent': 'true' } ] },
  { 'dungeons': [ 0x13, 0b0000 ], 'java': [ 'minecraft:sponge' ] },
  { 'dungeons': [ 0x14, 0b0000 ], 'java': [ 'minecraft:glass' ] },
  { 'dungeons': [ 0x15, 0b0000 ], 'java': [ 'minecraft:lapis_ore' ] },
  { 'dungeons': [ 0x16, 0b0000 ], 'java': [ 'minecraft:lapis_block' ] },
  { 'dungeons': [ 0x17, 0b0000 ], 'java': [ 'minecraft:dispenser', { 'facing': 'down' } ] },
  { 'dungeons': [ 0x17, 0b0001 ], 'java': [ 'minecraft:dispenser', { 'facing': 'up' } ] },
  { 'dungeons': [ 0x17, 0b0010 ], 'java': [ 'minecraft:dispenser', { 'facing': 'north' } ] },
  { 'dungeons': [ 0x17, 0b0011 ], 'java': [ 'minecraft:dispenser', { 'facing': 'south' } ] },
  { 'dungeons': [ 0x17, 0b0100 ], 'java': [ 'minecraft:dispenser', { 'facing': 'west' } ] },
  { 'dungeons': [ 0x17, 0b0101 ], 'java': [ 'minecraft:dispenser', { 'facing': 'east' } ] },
  { 'dungeons': [ 0x17, 0b1000 ], 'java': [ 'minecraft:dispenser', { 'facing': 'down' } ] },
  { 'dungeons': [ 0x17, 0b1001 ], 'java': [ 'minecraft:dispenser', { 'facing': 'up' } ] },
  { 'dungeons': [ 0x17, 0b1010 ], 'java': [ 'minecraft:dispenser', { 'facing': 'north' } ] },
  { 'dungeons': [ 0x17, 0b1011 ], 'java': [ 'minecraft:dispenser', { 'facing': 'south' } ] },
  { 'dungeons': [ 0x17, 0b1100 ], 'java': [ 'minecraft:dispenser', { 'facing': 'west' } ] },
  { 'dungeons': [ 0x17, 0b1101 ], 'java': [ 'minecraft:dispenser', { 'facing': 'east' } ] },
  { 'dungeons': [ 0x18, 0b0000 ], 'java': [ 'minecraft:sandstone' ] },
  { 'dungeons': [ 0x18, 0b0001 ], 'java': [ 'minecraft:chiseled_sandstone' ] },
  { 'dungeons': [ 0x18, 0b0010 ], 'java': [ 'minecraft:cut_sandstone' ] },
  { 'dungeons': [ 0x18, 0b0011 ], 'java': [ 'minecraft:smooth_sandstone' ] },
  { 'dungeons': [ 0x19, 0b0000 ], 'java': [ 'minecraft:noteblock' ] },
  { 'dungeons': [ 0x1a, 0b0000 ], 'java': [ 'minecraft:red_bed', { 'part': 'foot', 'occupied': 'false', 'facing': 'south' } ] },
  { 'dungeons': [ 0x1a, 0b0001 ], 'java': [ 'minecraft:red_bed', { 'part': 'foot', 'occupied': 'false', 'facing': 'west' } ] },
  { 'dungeons': [ 0x1a, 0b0010 ], 'java': [ 'minecraft:red_bed', { 'part': 'foot', 'occupied': 'false', 'facing': 'north' } ] },
  { 'dungeons': [ 0x1a, 0b0011 ], 'java': [ 'minecraft:red_bed', { 'part': 'foot', 'occupied': 'false', 'facing': 'east' } ] },
  { 'dungeons': [ 0x1a, 0b0100 ], 'java': [ 'minecraft:red_bed', { 'part': 'foot', 'occupied': 'true', 'facing': 'south' } ] },
  { 'dungeons': [ 0x1a, 0b0101 ], 'java': [ 'minecraft:red_bed', { 'part': 'foot', 'occupied': 'true', 'facing': 'west' } ] },
  { 'dungeons': [ 0x1a, 0b0110 ], 'java': [ 'minecraft:red_bed', { 'part': 'foot', 'occupied': 'true', 'facing': 'north' } ] },
  { 'dungeons': [ 0x1a, 0b0111 ], 'java': [ 'minecraft:red_bed', { 'part': 'foot', 'occupied': 'true', 'facing': 'east' } ] },
  { 'dungeons': [ 0x1a, 0b1000 ], 'java': [ 'minecraft:red_bed', { 'part': 'head', 'occupied': 'false', 'facing': 'south' } ] },
  { 'dungeons': [ 0x1a, 0b1001 ], 'java': [ 'minecraft:red_bed', { 'part': 'head', 'occupied': 'false', 'facing': 'west' } ] },
  { 'dungeons': [ 0x1a, 0b1010 ], 'java': [ 'minecraft:red_bed', { 'part': 'head', 'occupied': 'false', 'facing': 'north' } ] },
  { 'dungeons': [ 0x1a, 0b1011 ], 'java': [ 'minecraft:red_bed', { 'part': 'head', 'occupied': 'false', 'facing': 'east' } ] },
  { 'dungeons': [ 0x1a, 0b1100 ], 'java': [ 'minecraft:red_bed', { 'part': 'head', 'occupied': 'true', 'facing': 'south' } ] },
  { 'dungeons': [ 0x1a, 0b1101 ], 'java': [ 'minecraft:red_bed', { 'part': 'head', 'occupied': 'true', 'facing': 'west' } ] },
  { 'dungeons': [ 0x1a, 0b1110 ], 'java': [ 'minecraft:red_bed', { 'part': 'head', 'occupied': 'true', 'facing': 'north' } ] },
  { 'dungeons': [ 0x1a, 0b1111 ], 'java': [ 'minecraft:red_bed', { 'part': 'head', 'occupied': 'true', 'facing': 'east' } ] },
  { 'dungeons': [ 0x1b, 0b0000 ], 'java': [ 'minecraft:powered_rail', { 'powered': 'false', 'shape': 'north_south' } ] },
  { 'dungeons': [ 0x1b, 0b0001 ], 'java': [ 'minecraft:powered_rail', { 'powered': 'false', 'shape': 'east_west' } ] },
  { 'dungeons': [ 0x1b, 0b0010 ], 'java': [ 'minecraft:powered_rail', { 'powered': 'false', 'shape': 'ascending_east' } ] },
  { 'dungeons': [ 0x1b, 0b0011 ], 'java': [ 'minecraft:powered_rail', { 'powered': 'false', 'shape': 'ascending_west' } ] },
  { 'dungeons': [ 0x1b, 0b0100 ], 'java': [ 'minecraft:powered_rail', { 'powered': 'false', 'shape': 'ascending_north' } ] },
  { 'dungeons': [ 0x1b, 0b0101 ], 'java': [ 'minecraft:powered_rail', { 'powered': 'false', 'shape': 'ascending_south' } ] },
  { 'dungeons': [ 0x1b, 0b1000 ], 'java': [ 'minecraft:powered_rail', { 'powered': 'true', 'shape': 'north_south' } ] },
  { 'dungeons': [ 0x1b, 0b1001 ], 'java': [ 'minecraft:powered_rail', { 'powered': 'true', 'shape': 'east_west' } ] },
  { 'dungeons': [ 0x1b, 0b1010 ], 'java': [ 'minecraft:powered_rail', { 'powered': 'true', 'shape': 'ascending_east' } ] },
  { 'dungeons': [ 0x1b, 0b1011 ], 'java': [ 'minecraft:powered_rail', { 'powered': 'true', 'shape': 'ascending_west' } ] },
  { 'dungeons': [ 0x1b, 0b1100 ], 'java': [ 'minecraft:powered_rail', { 'powered': 'true', 'shape': 'ascending_north' } ] },
  { 'dungeons': [ 0x1b, 0b1101 ], 'java': [ 'minecraft:powered_rail', { 'powered': 'true', 'shape': 'ascending_south' } ] },
  { 'dungeons': [ 0x1c, 0b0000 ], 'java': [ 'minecraft:detector_rail', { 'powered': 'false', 'shape': 'north_south' } ] },
  { 'dungeons': [ 0x1c, 0b0001 ], 'java': [ 'minecraft:detector_rail', { 'powered': 'false', 'shape': 'east_west' } ] },
  { 'dungeons': [ 0x1c, 0b0010 ], 'java': [ 'minecraft:detector_rail', { 'powered': 'false', 'shape': 'ascending_east' } ] },
  { 'dungeons': [ 0x1c, 0b0011 ], 'java': [ 'minecraft:detector_rail', { 'powered': 'false', 'shape': 'ascending_west' } ] },
  { 'dungeons': [ 0x1c, 0b0100 ], 'java': [ 'minecraft:detector_rail', { 'powered': 'false', 'shape': 'ascending_north' } ] },
  { 'dungeons': [ 0x1c, 0b0101 ], 'java': [ 'minecraft:detector_rail', { 'powered': 'false', 'shape': 'ascending_south' } ] },
  { 'dungeons': [ 0x1c, 0b1000 ], 'java': [ 'minecraft:detector_rail', { 'powered': 'true', 'shape': 'north_south' } ] },
  { 'dungeons': [ 0x1c, 0b1001 ], 'java': [ 'minecraft:detector_rail', { 'powered': 'true', 'shape': 'east_west' } ] },
  { 'dungeons': [ 0x1c, 0b1010 ], 'java': [ 'minecraft:detector_rail', { 'powered': 'true', 'shape': 'ascending_east' } ] },
  { 'dungeons': [ 0x1c, 0b1011 ], 'java': [ 'minecraft:detector_rail', { 'powered': 'true', 'shape': 'ascending_west' } ] },
  { 'dungeons': [ 0x1c, 0b1100 ], 'java': [ 'minecraft:detector_rail', { 'powered': 'true', 'shape': 'ascending_north' } ] },
  { 'dungeons': [ 0x1c, 0b1101 ], 'java': [ 'minecraft:detector_rail', { 'powered': 'true', 'shape': 'ascending_south' } ] },
  { 'dungeons': [ 0x1d, 0b0000 ], 'java': [ 'minecraft:sticky_piston', { 'extended': 'false', 'facing': 'down' } ] },
  { 'dungeons': [ 0x1d, 0b0001 ], 'java': [ 'minecraft:sticky_piston', { 'extended': 'false', 'facing': 'up' } ] },
  { 'dungeons': [ 0x1d, 0b0010 ], 'java': [ 'minecraft:sticky_piston', { 'extended': 'false', 'facing': 'north' } ] },
  { 'dungeons': [ 0x1d, 0b0011 ], 'java': [ 'minecraft:sticky_piston', { 'extended': 'false', 'facing': 'south' } ] },
  { 'dungeons': [ 0x1d, 0b0100 ], 'java': [ 'minecraft:sticky_piston', { 'extended': 'false', 'facing': 'west' } ] },
  { 'dungeons': [ 0x1d, 0b0101 ], 'java': [ 'minecraft:sticky_piston', { 'extended': 'false', 'facing': 'east' } ] },
  { 'dungeons': [ 0x1d, 0b1000 ], 'java': [ 'minecraft:sticky_piston', { 'extended': 'true', 'facing': 'down' } ] },
  { 'dungeons': [ 0x1d, 0b1001 ], 'java': [ 'minecraft:sticky_piston', { 'extended': 'true', 'facing': 'up' } ] },
  { 'dungeons': [ 0x1d, 0b1010 ], 'java': [ 'minecraft:sticky_piston', { 'extended': 'true', 'facing': 'north' } ] },
  { 'dungeons': [ 0x1d, 0b1011 ], 'java': [ 'minecraft:sticky_piston', { 'extended': 'true', 'facing': 'south' } ] },
  { 'dungeons': [ 0x1d, 0b1100 ], 'java': [ 'minecraft:sticky_piston', { 'extended': 'true', 'facing': 'west' } ] },
  { 'dungeons': [ 0x1d, 0b1101 ], 'java': [ 'minecraft:sticky_piston', { 'extended': 'true', 'facing': 'east' } ] },
  { 'dungeons': [ 0x1e, 0b0000 ], 'java': [ 'minecraft:cobweb' ] },
  { 'dungeons': [ 0x1f, 0b0001 ], 'java': [ 'minecraft:grass' ] },
  { 'dungeons': [ 0x1f, 0b0010 ], 'java': [ 'minecraft:fern' ] },
  { 'dungeons': [ 0x23, 0b0000 ], 'java': [ 'minecraft:white_wool' ] },
  { 'dungeons': [ 0x23, 0b0001 ], 'java': [ 'minecraft:orange_wool' ] },
  { 'dungeons': [ 0x23, 0b0010 ], 'java': [ 'minecraft:magenta_wool' ] },
  { 'dungeons': [ 0x23, 0b0011 ], 'java': [ 'minecraft:light_blue_wool' ] },
  { 'dungeons': [ 0x23, 0b0100 ], 'java': [ 'minecraft:yellow_wool' ] },
  { 'dungeons': [ 0x23, 0b0101 ], 'java': [ 'minecraft:lime_wool' ] },
  { 'dungeons': [ 0x23, 0b0110 ], 'java': [ 'minecraft:pink_wool' ] },
  { 'dungeons': [ 0x23, 0b0111 ], 'java': [ 'minecraft:gray_wool' ] },
  { 'dungeons': [ 0x23, 0b1000 ], 'java': [ 'minecraft:light_gray_wool' ] },
  { 'dungeons': [ 0x23, 0b1001 ], 'java': [ 'minecraft:cyan_wool' ] },
  { 'dungeons': [ 0x23, 0b1010 ], 'java': [ 'minecraft:purple_wool' ] },
  { 'dungeons': [ 0x23, 0b1011 ], 'java': [ 'minecraft:blue_wool' ] },
  { 'dungeons': [ 0x23, 0b1100 ], 'java': [ 'minecraft:brown_wool' ] },
  { 'dungeons': [ 0x23, 0b1101 ], 'java': [ 'minecraft:green_wool' ] },
  { 'dungeons': [ 0x23, 0b1110 ], 'java': [ 'minecraft:red_wool' ] },
  { 'dungeons': [ 0x23, 0b1111 ], 'java': [ 'minecraft:black_wool' ] },
  { 'dungeons': [ 0x25, 0b0000 ], 'java': [ 'minecraft:dandelion' ] },
  { 'dungeons': [ 0x26, 0b0000 ], 'java': [ 'minecraft:poppy' ] },
  { 'dungeons': [ 0x26, 0b0001 ], 'java': [ 'minecraft:blue_orchid' ] },
  { 'dungeons': [ 0x26, 0b0010 ], 'java': [ 'minecraft:allium' ] },
  { 'dungeons': [ 0x26, 0b0011 ], 'java': [ 'minecraft:azure_bluet' ] },
  { 'dungeons': [ 0x26, 0b0100 ], 'java': [ 'minecraft:red_tulip' ] },
  { 'dungeons': [ 0x26, 0b0101 ], 'java': [ 'minecraft:orange_tulip' ] },
  { 'dungeons': [ 0x26, 0b0110 ], 'java': [ 'minecraft:white_tulip' ] },
  { 'dungeons': [ 0x26, 0b0111 ], 'java': [ 'minecraft:pink_tulip' ] },
  { 'dungeons': [ 0x26, 0b1000 ], 'java': [ 'minecraft:oxeye_daisy' ] },
  { 'dungeons': [ 0x26, 0b1001 ], 'java': [ 'minecraft:cornflower' ] },
  { 'dungeons': [ 0x26, 0b1010 ], 'java': [ 'minecraft:lily_of_the_valley' ] },
  { 'dungeons': [ 0x29, 0b0000 ], 'java': [ 'minecraft:gold_block' ] },
  { 'dungeons': [ 0x2a, 0b0000 ], 'java': [ 'minecraft:iron_block' ] },
  { 'dungeons': [ 0x2b, 0b0000 ], 'java': [ 'minecraft:smooth_stone_slab', { 'type': 'double' } ] },
  { 'dungeons': [ 0x2b, 0b0001 ], 'java': [ 'minecraft:sandstone_slab', { 'type': 'double' } ] },
  { 'dungeons': [ 0x2b, 0b0010 ], 'java': [ 'minecraft:petrified_oak_slab', { 'type': 'double' } ] },
  { 'dungeons': [ 0x2b, 0b0011 ], 'java': [ 'minecraft:cobblestone_slab', { 'type': 'double' } ] },
  { 'dungeons': [ 0x2b, 0b0100 ], 'java': [ 'minecraft:brick_slab', { 'type': 'double' } ] },
  { 'dungeons': [ 0x2b, 0b0101 ], 'java': [ 'minecraft:stone_brick_slab', { 'type': 'double' } ] },
  { 'dungeons': [ 0x2b, 0b0110 ], 'java': [ 'minecraft:quartz_slab', { 'type': 'double' } ] },
  { 'dungeons': [ 0x2b, 0b0111 ], 'java': [ 'minecraft:nether_brick_slab', { 'type': 'double' } ] },
  { 'dungeons': [ 0x2c, 0b0000 ], 'java': [ 'minecraft:smooth_stone_slab', { 'type': 'bottom' } ] },
  { 'dungeons': [ 0x2c, 0b0001 ], 'java': [ 'minecraft:sandstone_slab', { 'type': 'bottom' } ] },
  { 'dungeons': [ 0x2c, 0b0010 ], 'java': [ 'minecraft:petrified_oak_slab', { 'type': 'bottom' } ] },
  { 'dungeons': [ 0x2c, 0b0011 ], 'java': [ 'minecraft:cobblestone_slab', { 'type': 'bottom' } ] },
  { 'dungeons': [ 0x2c, 0b0100 ], 'java': [ 'minecraft:brick_slab', { 'type': 'bottom' } ] },
  { 'dungeons': [ 0x2c, 0b0101 ], 'java': [ 'minecraft:stone_brick_slab', { 'type': 'bottom' } ] },
  { 'dungeons': [ 0x2c, 0b0110 ], 'java': [ 'minecraft:quartz_slab', { 'type': 'bottom' } ] },
  { 'dungeons': [ 0x2c, 0b0111 ], 'java': [ 'minecraft:red_nether_brick_slab', { 'type': 'bottom' } ] },
  { 'dungeons': [ 0x2c, 0b1000 ], 'java': [ 'minecraft:smooth_stone_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0x2c, 0b1001 ], 'java': [ 'minecraft:sandstone_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0x2c, 0b1010 ], 'java': [ 'minecraft:petrified_oak_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0x2c, 0b1011 ], 'java': [ 'minecraft:cobblestone_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0x2c, 0b1100 ], 'java': [ 'minecraft:brick_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0x2c, 0b1101 ], 'java': [ 'minecraft:stone_brick_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0x2c, 0b1110 ], 'java': [ 'minecraft:quartz_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0x2c, 0b1111 ], 'java': [ 'minecraft:red_nether_brick_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0x2d, 0b0000 ], 'java': [ 'minecraft:bricks' ] },
  { 'dungeons': [ 0x2f, 0b0000 ], 'java': [ 'minecraft:bookshelf' ] },
  { 'dungeons': [ 0x30, 0b0000 ], 'java': [ 'minecraft:mossy_cobblestone' ] },
  { 'dungeons': [ 0x31, 0b0000 ], 'java': [ 'minecraft:obsidian' ] },
  { 'dungeons': [ 0x32, 0b0001 ], 'java': [ 'minecraft:wall_torch', { 'facing': 'east' } ] },
  { 'dungeons': [ 0x32, 0b0010 ], 'java': [ 'minecraft:wall_torch', { 'facing': 'west' } ] },
  { 'dungeons': [ 0x32, 0b0011 ], 'java': [ 'minecraft:wall_torch', { 'facing': 'south' } ] },
  { 'dungeons': [ 0x32, 0b0100 ], 'java': [ 'minecraft:wall_torch', { 'facing': 'north' } ] },
  { 'dungeons': [ 0x32, 0b0101 ], 'java': [ 'minecraft:torch' ] },
  { 'dungeons': [ 0x35, 0b0000 ], 'java': [ 'minecraft:oak_stairs', { 'facing': 'east', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x35, 0b0001 ], 'java': [ 'minecraft:oak_stairs', { 'facing': 'west', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x35, 0b0010 ], 'java': [ 'minecraft:oak_stairs', { 'facing': 'south', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x35, 0b0011 ], 'java': [ 'minecraft:oak_stairs', { 'facing': 'north', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x35, 0b0100 ], 'java': [ 'minecraft:oak_stairs', { 'facing': 'east', 'half': 'top' } ] },
  { 'dungeons': [ 0x35, 0b0101 ], 'java': [ 'minecraft:oak_stairs', { 'facing': 'west', 'half': 'top' } ] },
  { 'dungeons': [ 0x35, 0b0110 ], 'java': [ 'minecraft:oak_stairs', { 'facing': 'south', 'half': 'top' } ] },
  { 'dungeons': [ 0x35, 0b0111 ], 'java': [ 'minecraft:oak_stairs', { 'facing': 'north', 'half': 'top' } ] },
  { 'dungeons': [ 0x36, 0b0010 ], 'java': [ 'minecraft:chest', { 'facing': 'north' } ] },
  { 'dungeons': [ 0x36, 0b0011 ], 'java': [ 'minecraft:chest', { 'facing': 'south' } ] },
  { 'dungeons': [ 0x36, 0b0100 ], 'java': [ 'minecraft:chest', { 'facing': 'west' } ] },
  { 'dungeons': [ 0x36, 0b0101 ], 'java': [ 'minecraft:chest', { 'facing': 'east' } ] },
  { 'dungeons': [ 0x37, 0b0000 ], 'java': [ 'minecraft:redstone_wire', { 'power': '0' } ] },
  { 'dungeons': [ 0x37, 0b0001 ], 'java': [ 'minecraft:redstone_wire', { 'power': '1' } ] },
  { 'dungeons': [ 0x37, 0b0010 ], 'java': [ 'minecraft:redstone_wire', { 'power': '2' } ] },
  { 'dungeons': [ 0x37, 0b0011 ], 'java': [ 'minecraft:redstone_wire', { 'power': '3' } ] },
  { 'dungeons': [ 0x37, 0b0100 ], 'java': [ 'minecraft:redstone_wire', { 'power': '4' } ] },
  { 'dungeons': [ 0x37, 0b0101 ], 'java': [ 'minecraft:redstone_wire', { 'power': '5' } ] },
  { 'dungeons': [ 0x37, 0b0110 ], 'java': [ 'minecraft:redstone_wire', { 'power': '6' } ] },
  { 'dungeons': [ 0x37, 0b0111 ], 'java': [ 'minecraft:redstone_wire', { 'power': '7' } ] },
  { 'dungeons': [ 0x37, 0b1000 ], 'java': [ 'minecraft:redstone_wire', { 'power': '8' } ] },
  { 'dungeons': [ 0x37, 0b1001 ], 'java': [ 'minecraft:redstone_wire', { 'power': '9' } ] },
  { 'dungeons': [ 0x37, 0b1010 ], 'java': [ 'minecraft:redstone_wire', { 'power': '10' } ] },
  { 'dungeons': [ 0x37, 0b1011 ], 'java': [ 'minecraft:redstone_wire', { 'power': '11' } ] },
  { 'dungeons': [ 0x37, 0b1100 ], 'java': [ 'minecraft:redstone_wire', { 'power': '12' } ] },
  { 'dungeons': [ 0x37, 0b1101 ], 'java': [ 'minecraft:redstone_wire', { 'power': '13' } ] },
  { 'dungeons': [ 0x37, 0b1110 ], 'java': [ 'minecraft:redstone_wire', { 'power': '14' } ] },
  { 'dungeons': [ 0x37, 0b1111 ], 'java': [ 'minecraft:redstone_wire', { 'power': '15' } ] },
  { 'dungeons': [ 0x38, 0b0000 ], 'java': [ 'minecraft:diamond_ore' ] },
  { 'dungeons': [ 0x39, 0b0000 ], 'java': [ 'minecraft:diamond_block' ] },
  { 'dungeons': [ 0x3a, 0b0000 ], 'java': [ 'minecraft:crafting_table' ] },
  { 'dungeons': [ 0x3b, 0b0000 ], 'java': [ 'minecraft:wheat', { 'age': '0' } ] },
  { 'dungeons': [ 0x3b, 0b0001 ], 'java': [ 'minecraft:wheat', { 'age': '1' } ] },
  { 'dungeons': [ 0x3b, 0b0010 ], 'java': [ 'minecraft:wheat', { 'age': '2' } ] },
  { 'dungeons': [ 0x3b, 0b0011 ], 'java': [ 'minecraft:wheat', { 'age': '3' } ] },
  { 'dungeons': [ 0x3b, 0b0100 ], 'java': [ 'minecraft:wheat', { 'age': '4' } ] },
  { 'dungeons': [ 0x3b, 0b0101 ], 'java': [ 'minecraft:wheat', { 'age': '5' } ] },
  { 'dungeons': [ 0x3b, 0b0110 ], 'java': [ 'minecraft:wheat', { 'age': '6' } ] },
  { 'dungeons': [ 0x3b, 0b0111 ], 'java': [ 'minecraft:wheat', { 'age': '7' } ] },
  { 'dungeons': [ 0x3c, 0b0000 ], 'java': [ 'minecraft:farmland', { 'moisture': '0' } ] },
  { 'dungeons': [ 0x3c, 0b0111 ], 'java': [ 'minecraft:farmland', { 'moisture': '7' } ] },
  { 'dungeons': [ 0x3d, 0b0010 ], 'java': [ 'minecraft:furnace', { 'facing': 'north' } ] },
  { 'dungeons': [ 0x3d, 0b0011 ], 'java': [ 'minecraft:furnace', { 'facing': 'south' } ] },
  { 'dungeons': [ 0x3d, 0b0100 ], 'java': [ 'minecraft:furnace', { 'facing': 'west' } ] },
  { 'dungeons': [ 0x3d, 0b0101 ], 'java': [ 'minecraft:furnace', { 'facing': 'east' } ] },
  { 'dungeons': [ 0x3f, 0b0000 ], 'java': [ 'minecraft:oak_sign', { 'rotation': '0' } ] },
  { 'dungeons': [ 0x3f, 0b0001 ], 'java': [ 'minecraft:oak_sign', { 'rotation': '1' } ] },
  { 'dungeons': [ 0x3f, 0b0010 ], 'java': [ 'minecraft:oak_sign', { 'rotation': '2' } ] },
  { 'dungeons': [ 0x3f, 0b0011 ], 'java': [ 'minecraft:oak_sign', { 'rotation': '3' } ] },
  { 'dungeons': [ 0x3f, 0b0100 ], 'java': [ 'minecraft:oak_sign', { 'rotation': '4' } ] },
  { 'dungeons': [ 0x3f, 0b0101 ], 'java': [ 'minecraft:oak_sign', { 'rotation': '5' } ] },
  { 'dungeons': [ 0x3f, 0b0110 ], 'java': [ 'minecraft:oak_sign', { 'rotation': '6' } ] },
  { 'dungeons': [ 0x3f, 0b0111 ], 'java': [ 'minecraft:oak_sign', { 'rotation': '7' } ] },
  { 'dungeons': [ 0x3f, 0b1000 ], 'java': [ 'minecraft:oak_sign', { 'rotation': '8' } ] },
  { 'dungeons': [ 0x3f, 0b1001 ], 'java': [ 'minecraft:oak_sign', { 'rotation': '9' } ] },
  { 'dungeons': [ 0x3f, 0b1010 ], 'java': [ 'minecraft:oak_sign', { 'rotation': '10' } ] },
  { 'dungeons': [ 0x3f, 0b1011 ], 'java': [ 'minecraft:oak_sign', { 'rotation': '11' } ] },
  { 'dungeons': [ 0x3f, 0b1100 ], 'java': [ 'minecraft:oak_sign', { 'rotation': '12' } ] },
  { 'dungeons': [ 0x3f, 0b1101 ], 'java': [ 'minecraft:oak_sign', { 'rotation': '13' } ] },
  { 'dungeons': [ 0x3f, 0b1110 ], 'java': [ 'minecraft:oak_sign', { 'rotation': '14' } ] },
  { 'dungeons': [ 0x3f, 0b1111 ], 'java': [ 'minecraft:oak_sign', { 'rotation': '15' } ] },
  { 'dungeons': [ 0x41, 0b0010, 0b0111 ], 'java': [ 'minecraft:ladder', { 'facing': 'north' } ] },
  { 'dungeons': [ 0x41, 0b0011, 0b0111 ], 'java': [ 'minecraft:ladder', { 'facing': 'south' } ] },
  { 'dungeons': [ 0x41, 0b0100, 0b0111 ], 'java': [ 'minecraft:ladder', { 'facing': 'west' } ] },
  { 'dungeons': [ 0x41, 0b0101, 0b0111 ], 'java': [ 'minecraft:ladder', { 'facing': 'east' } ] },
  { 'dungeons': [ 0x42, 0b0000 ], 'java': [ 'minecraft:rail', { 'shape': 'north_south' } ] },
  { 'dungeons': [ 0x42, 0b0001 ], 'java': [ 'minecraft:rail', { 'shape': 'east_west' } ] },
  { 'dungeons': [ 0x42, 0b0010 ], 'java': [ 'minecraft:rail', { 'shape': 'ascending_east' } ] },
  { 'dungeons': [ 0x42, 0b0011 ], 'java': [ 'minecraft:rail', { 'shape': 'ascending_west' } ] },
  { 'dungeons': [ 0x42, 0b0100 ], 'java': [ 'minecraft:rail', { 'shape': 'ascending_north' } ] },
  { 'dungeons': [ 0x42, 0b0101 ], 'java': [ 'minecraft:rail', { 'shape': 'ascending_south' } ] },
  { 'dungeons': [ 0x42, 0b0110 ], 'java': [ 'minecraft:rail', { 'shape': 'south_east' } ] },
  { 'dungeons': [ 0x42, 0b0111 ], 'java': [ 'minecraft:rail', { 'shape': 'south_west' } ] },
  { 'dungeons': [ 0x42, 0b1000 ], 'java': [ 'minecraft:rail', { 'shape': 'north_west' } ] },
  { 'dungeons': [ 0x42, 0b1001 ], 'java': [ 'minecraft:rail', { 'shape': 'north_east' } ] },
  { 'dungeons': [ 0x43, 0b0000 ], 'java': [ 'minecraft:cobblestone_stairs', { 'facing': 'east', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x43, 0b0001 ], 'java': [ 'minecraft:cobblestone_stairs', { 'facing': 'west', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x43, 0b0010 ], 'java': [ 'minecraft:cobblestone_stairs', { 'facing': 'south', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x43, 0b0011 ], 'java': [ 'minecraft:cobblestone_stairs', { 'facing': 'north', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x43, 0b0100 ], 'java': [ 'minecraft:cobblestone_stairs', { 'facing': 'east', 'half': 'top' } ] },
  { 'dungeons': [ 0x43, 0b0101 ], 'java': [ 'minecraft:cobblestone_stairs', { 'facing': 'west', 'half': 'top' } ] },
  { 'dungeons': [ 0x43, 0b0110 ], 'java': [ 'minecraft:cobblestone_stairs', { 'facing': 'south', 'half': 'top' } ] },
  { 'dungeons': [ 0x43, 0b0111 ], 'java': [ 'minecraft:cobblestone_stairs', { 'facing': 'north', 'half': 'top' } ] },
  { 'dungeons': [ 0x44, 0b0010 ], 'java': [ 'minecraft:oak_wall_sign', { 'facing': 'north' } ] },
  { 'dungeons': [ 0x44, 0b0011 ], 'java': [ 'minecraft:oak_wall_sign', { 'facing': 'south' } ] },
  { 'dungeons': [ 0x44, 0b0100 ], 'java': [ 'minecraft:oak_wall_sign', { 'facing': 'west' } ] },
  { 'dungeons': [ 0x44, 0b0101 ], 'java': [ 'minecraft:oak_wall_sign', { 'facing': 'east' } ] },
  { 'dungeons': [ 0x4e, 0b0000, 0b0111 ], 'java': [ 'minecraft:snow', { 'layers': '1' } ] },
  { 'dungeons': [ 0x4e, 0b0001, 0b0111 ], 'java': [ 'minecraft:snow', { 'layers': '2' } ] },
  { 'dungeons': [ 0x4e, 0b0010, 0b0111 ], 'java': [ 'minecraft:snow', { 'layers': '3' } ] },
  { 'dungeons': [ 0x4e, 0b0011, 0b0111 ], 'java': [ 'minecraft:snow', { 'layers': '4' } ] },
  { 'dungeons': [ 0x4e, 0b0100, 0b0111 ], 'java': [ 'minecraft:snow', { 'layers': '5' } ] },
  { 'dungeons': [ 0x4e, 0b0101, 0b0111 ], 'java': [ 'minecraft:snow', { 'layers': '6' } ] },
  { 'dungeons': [ 0x4e, 0b0110, 0b0111 ], 'java': [ 'minecraft:snow', { 'layers': '7' } ] },
  { 'dungeons': [ 0x4e, 0b0111, 0b0111 ], 'java': [ 'minecraft:snow', { 'layers': '8' } ] },
  { 'dungeons': [ 0x4f, 0b0000 ], 'java': [ 'minecraft:ice' ] },
  { 'dungeons': [ 0x50, 0b0000 ], 'java': [ 'minecraft:snow_block' ] },
  { 'dungeons': [ 0x52, 0b0000 ], 'java': [ 'minecraft:clay' ] },
  { 'dungeons': [ 0x53, 0b0000 ], 'java': [ 'minecraft:sugar_cane', { 'age': '0' } ] },
  { 'dungeons': [ 0x53, 0b0001 ], 'java': [ 'minecraft:sugar_cane', { 'age': '1' } ] },
  { 'dungeons': [ 0x53, 0b0010 ], 'java': [ 'minecraft:sugar_cane', { 'age': '2' } ] },
  { 'dungeons': [ 0x53, 0b0011 ], 'java': [ 'minecraft:sugar_cane', { 'age': '3' } ] },
  { 'dungeons': [ 0x53, 0b0100 ], 'java': [ 'minecraft:sugar_cane', { 'age': '4' } ] },
  { 'dungeons': [ 0x53, 0b0101 ], 'java': [ 'minecraft:sugar_cane', { 'age': '5' } ] },
  { 'dungeons': [ 0x53, 0b0110 ], 'java': [ 'minecraft:sugar_cane', { 'age': '6' } ] },
  { 'dungeons': [ 0x53, 0b0111 ], 'java': [ 'minecraft:sugar_cane', { 'age': '7' } ] },
  { 'dungeons': [ 0x53, 0b1000 ], 'java': [ 'minecraft:sugar_cane', { 'age': '8' } ] },
  { 'dungeons': [ 0x53, 0b1001 ], 'java': [ 'minecraft:sugar_cane', { 'age': '9' } ] },
  { 'dungeons': [ 0x53, 0b1010 ], 'java': [ 'minecraft:sugar_cane', { 'age': '10' } ] },
  { 'dungeons': [ 0x53, 0b1011 ], 'java': [ 'minecraft:sugar_cane', { 'age': '11' } ] },
  { 'dungeons': [ 0x53, 0b1100 ], 'java': [ 'minecraft:sugar_cane', { 'age': '12' } ] },
  { 'dungeons': [ 0x53, 0b1101 ], 'java': [ 'minecraft:sugar_cane', { 'age': '13' } ] },
  { 'dungeons': [ 0x53, 0b1110 ], 'java': [ 'minecraft:sugar_cane', { 'age': '14' } ] },
  { 'dungeons': [ 0x53, 0b1111 ], 'java': [ 'minecraft:sugar_cane', { 'age': '15' } ] },
  { 'dungeons': [ 0x55, 0b0000 ], 'java': [ 'minecraft:oak_fence' ] },
  { 'dungeons': [ 0x55, 0b0001 ], 'java': [ 'minecraft:spruce_fence' ] },
  { 'dungeons': [ 0x55, 0b0010 ], 'java': [ 'minecraft:birch_fence' ] },
  { 'dungeons': [ 0x55, 0b0011 ], 'java': [ 'minecraft:jungle_fence' ] },
  { 'dungeons': [ 0x55, 0b0100 ], 'java': [ 'minecraft:acacia_fence' ] },
  { 'dungeons': [ 0x55, 0b0101 ], 'java': [ 'minecraft:dark_oak_fence' ] },
  { 'dungeons': [ 0x56, 0b0000 ], 'java': [ 'minecraft:carved_pumpkin', { 'facing': 'east' } ] },
  { 'dungeons': [ 0x56, 0b0001 ], 'java': [ 'minecraft:carved_pumpkin', { 'facing': 'west' } ] },
  { 'dungeons': [ 0x56, 0b0010 ], 'java': [ 'minecraft:carved_pumpkin', { 'facing': 'north' } ] },
  { 'dungeons': [ 0x56, 0b0011 ], 'java': [ 'minecraft:carved_pumpkin', { 'facing': 'south' } ] },
  { 'dungeons': [ 0x57, 0b0000 ], 'java': [ 'minecraft:netherrack' ] },
  { 'dungeons': [ 0x58, 0b0000 ], 'java': [ 'minecraft:soul_sand' ] },
  { 'dungeons': [ 0x59, 0b0000 ], 'java': [ 'minecraft:glowstone' ] },
  { 'dungeons': [ 0x5b, 0b0000 ], 'java': [ 'minecraft:jack_o_lantern', { 'facing': 'south' } ] },
  { 'dungeons': [ 0x5b, 0b0001 ], 'java': [ 'minecraft:jack_o_lantern', { 'facing': 'west' } ] },
  { 'dungeons': [ 0x5b, 0b0010 ], 'java': [ 'minecraft:jack_o_lantern', { 'facing': 'north' } ] },
  { 'dungeons': [ 0x5b, 0b0011 ], 'java': [ 'minecraft:jack_o_lantern', { 'facing': 'east' } ] },
  { 'dungeons': [ 0x5d, 0b0000 ], 'java': [ 'minecraft:repeater', { 'facing': 'north', 'delay': '1', 'powered': 'false' } ] },
  { 'dungeons': [ 0x5d, 0b0001 ], 'java': [ 'minecraft:repeater', { 'facing': 'east',  'delay': '1', 'powered': 'false' } ] },
  { 'dungeons': [ 0x5d, 0b0010 ], 'java': [ 'minecraft:repeater', { 'facing': 'south', 'delay': '1', 'powered': 'false' } ] },
  { 'dungeons': [ 0x5d, 0b0011 ], 'java': [ 'minecraft:repeater', { 'facing': 'west',  'delay': '1', 'powered': 'false' } ] },
  { 'dungeons': [ 0x5d, 0b0100 ], 'java': [ 'minecraft:repeater', { 'facing': 'north', 'delay': '2', 'powered': 'false' } ] },
  { 'dungeons': [ 0x5d, 0b0101 ], 'java': [ 'minecraft:repeater', { 'facing': 'east',  'delay': '2', 'powered': 'false' } ] },
  { 'dungeons': [ 0x5d, 0b0110 ], 'java': [ 'minecraft:repeater', { 'facing': 'south', 'delay': '2', 'powered': 'false' } ] },
  { 'dungeons': [ 0x5d, 0b0111 ], 'java': [ 'minecraft:repeater', { 'facing': 'west',  'delay': '2', 'powered': 'false' } ] },
  { 'dungeons': [ 0x5d, 0b1000 ], 'java': [ 'minecraft:repeater', { 'facing': 'north', 'delay': '3', 'powered': 'false' } ] },
  { 'dungeons': [ 0x5d, 0b1001 ], 'java': [ 'minecraft:repeater', { 'facing': 'east',  'delay': '3', 'powered': 'false' } ] },
  { 'dungeons': [ 0x5d, 0b1010 ], 'java': [ 'minecraft:repeater', { 'facing': 'south', 'delay': '3', 'powered': 'false' } ] },
  { 'dungeons': [ 0x5d, 0b1011 ], 'java': [ 'minecraft:repeater', { 'facing': 'west',  'delay': '3', 'powered': 'false' } ] },
  { 'dungeons': [ 0x5d, 0b1100 ], 'java': [ 'minecraft:repeater', { 'facing': 'north', 'delay': '4', 'powered': 'false' } ] },
  { 'dungeons': [ 0x5d, 0b1101 ], 'java': [ 'minecraft:repeater', { 'facing': 'east',  'delay': '4', 'powered': 'false' } ] },
  { 'dungeons': [ 0x5d, 0b1110 ], 'java': [ 'minecraft:repeater', { 'facing': 'south', 'delay': '4', 'powered': 'false' } ] },
  { 'dungeons': [ 0x5d, 0b1111 ], 'java': [ 'minecraft:repeater', { 'facing': 'west',  'delay': '4', 'powered': 'false' } ] },
  { 'dungeons': [ 0x5e, 0b0000 ], 'java': [ 'minecraft:repeater', { 'facing': 'north', 'delay': '1', 'powered': 'true' } ] },
  { 'dungeons': [ 0x5e, 0b0001 ], 'java': [ 'minecraft:repeater', { 'facing': 'east',  'delay': '1', 'powered': 'true' } ] },
  { 'dungeons': [ 0x5e, 0b0010 ], 'java': [ 'minecraft:repeater', { 'facing': 'south', 'delay': '1', 'powered': 'true' } ] },
  { 'dungeons': [ 0x5e, 0b0011 ], 'java': [ 'minecraft:repeater', { 'facing': 'west',  'delay': '1', 'powered': 'true' } ] },
  { 'dungeons': [ 0x5e, 0b0100 ], 'java': [ 'minecraft:repeater', { 'facing': 'north', 'delay': '2', 'powered': 'true' } ] },
  { 'dungeons': [ 0x5e, 0b0101 ], 'java': [ 'minecraft:repeater', { 'facing': 'east',  'delay': '2', 'powered': 'true' } ] },
  { 'dungeons': [ 0x5e, 0b0110 ], 'java': [ 'minecraft:repeater', { 'facing': 'south', 'delay': '2', 'powered': 'true' } ] },
  { 'dungeons': [ 0x5e, 0b0111 ], 'java': [ 'minecraft:repeater', { 'facing': 'west',  'delay': '2', 'powered': 'true' } ] },
  { 'dungeons': [ 0x5e, 0b1000 ], 'java': [ 'minecraft:repeater', { 'facing': 'north', 'delay': '3', 'powered': 'true' } ] },
  { 'dungeons': [ 0x5e, 0b1001 ], 'java': [ 'minecraft:repeater', { 'facing': 'east',  'delay': '3', 'powered': 'true' } ] },
  { 'dungeons': [ 0x5e, 0b1010 ], 'java': [ 'minecraft:repeater', { 'facing': 'south', 'delay': '3', 'powered': 'true' } ] },
  { 'dungeons': [ 0x5e, 0b1011 ], 'java': [ 'minecraft:repeater', { 'facing': 'west',  'delay': '3', 'powered': 'true' } ] },
  { 'dungeons': [ 0x5e, 0b1100 ], 'java': [ 'minecraft:repeater', { 'facing': 'north', 'delay': '4', 'powered': 'true' } ] },
  { 'dungeons': [ 0x5e, 0b1101 ], 'java': [ 'minecraft:repeater', { 'facing': 'east',  'delay': '4', 'powered': 'true' } ] },
  { 'dungeons': [ 0x5e, 0b1110 ], 'java': [ 'minecraft:repeater', { 'facing': 'south', 'delay': '4', 'powered': 'true' } ] },
  { 'dungeons': [ 0x5e, 0b1111 ], 'java': [ 'minecraft:repeater', { 'facing': 'west',  'delay': '4', 'powered': 'true' } ] },
  { 'dungeons': [ 0x60, 0b0000 ], 'java': [ 'minecraft:oak_trapdoor', { 'open': 'false', 'half': 'bottom', 'facing': 'east' } ] },
  { 'dungeons': [ 0x60, 0b0001 ], 'java': [ 'minecraft:oak_trapdoor', { 'open': 'false', 'half': 'bottom', 'facing': 'west' } ] },
  { 'dungeons': [ 0x60, 0b0010 ], 'java': [ 'minecraft:oak_trapdoor', { 'open': 'false', 'half': 'bottom', 'facing': 'south' } ] },
  { 'dungeons': [ 0x60, 0b0011 ], 'java': [ 'minecraft:oak_trapdoor', { 'open': 'false', 'half': 'bottom', 'facing': 'north' } ] },
  { 'dungeons': [ 0x60, 0b0100 ], 'java': [ 'minecraft:oak_trapdoor', { 'open': 'false', 'half': 'top', 'facing': 'east' } ] },
  { 'dungeons': [ 0x60, 0b0101 ], 'java': [ 'minecraft:oak_trapdoor', { 'open': 'false', 'half': 'top', 'facing': 'west' } ] },
  { 'dungeons': [ 0x60, 0b0110 ], 'java': [ 'minecraft:oak_trapdoor', { 'open': 'false', 'half': 'top', 'facing': 'south' } ] },
  { 'dungeons': [ 0x60, 0b0111 ], 'java': [ 'minecraft:oak_trapdoor', { 'open': 'false', 'half': 'top', 'facing': 'north' } ] },
  { 'dungeons': [ 0x60, 0b1000 ], 'java': [ 'minecraft:oak_trapdoor', { 'open': 'true', 'half': 'bottom', 'facing': 'east' } ] },
  { 'dungeons': [ 0x60, 0b1001 ], 'java': [ 'minecraft:oak_trapdoor', { 'open': 'true', 'half': 'bottom', 'facing': 'west' } ] },
  { 'dungeons': [ 0x60, 0b1010 ], 'java': [ 'minecraft:oak_trapdoor', { 'open': 'true', 'half': 'bottom', 'facing': 'south' } ] },
  { 'dungeons': [ 0x60, 0b1011 ], 'java': [ 'minecraft:oak_trapdoor', { 'open': 'true', 'half': 'bottom', 'facing': 'north' } ] },
  { 'dungeons': [ 0x60, 0b1100 ], 'java': [ 'minecraft:oak_trapdoor', { 'open': 'true', 'half': 'top', 'facing': 'east' } ] },
  { 'dungeons': [ 0x60, 0b1101 ], 'java': [ 'minecraft:oak_trapdoor', { 'open': 'true', 'half': 'top', 'facing': 'west' } ] },
  { 'dungeons': [ 0x60, 0b1110 ], 'java': [ 'minecraft:oak_trapdoor', { 'open': 'true', 'half': 'top', 'facing': 'south' } ] },
  { 'dungeons': [ 0x60, 0b1111 ], 'java': [ 'minecraft:oak_trapdoor', { 'open': 'true', 'half': 'top', 'facing': 'north' } ] },
  { 'dungeons': [ 0x62, 0b0000 ], 'java': [ 'minecraft:stone_bricks' ] },
  { 'dungeons': [ 0x62, 0b0001 ], 'java': [ 'minecraft:mossy_stone_bricks' ] },
  { 'dungeons': [ 0x62, 0b0010 ], 'java': [ 'minecraft:cracked_stone_bricks' ] },
  { 'dungeons': [ 0x62, 0b0011 ], 'java': [ 'minecraft:chiseled_stone_bricks' ] },
  { 'dungeons': [ 0x62, 0b0100 ], 'java': [ 'minecraft:netherite_block' ] },
  { 'dungeons': [ 0x63, 0b0000 ], 'java': [ 'minecraft:brown_mushroom_block', { 'east': 'false', 'west': 'false', 'north': 'false', 'south': 'false', 'up': 'false', 'down': 'false' } ] },
  { 'dungeons': [ 0x63, 0b0001 ], 'java': [ 'minecraft:brown_mushroom_block', { 'east': 'false', 'west': 'true', 'north': 'true', 'south': 'false', 'up': 'true', 'down': 'false' } ] },
  { 'dungeons': [ 0x63, 0b0010 ], 'java': [ 'minecraft:brown_mushroom_block', { 'east': 'false', 'west': 'false', 'north': 'true', 'south': 'false', 'up': 'true', 'down': 'false' } ] },
  { 'dungeons': [ 0x63, 0b0011 ], 'java': [ 'minecraft:brown_mushroom_block', { 'east': 'true', 'west': 'false', 'north': 'true', 'south': 'false', 'up': 'true', 'down': 'false' } ] },
  { 'dungeons': [ 0x63, 0b0100 ], 'java': [ 'minecraft:brown_mushroom_block', { 'east': 'false', 'west': 'true', 'north': 'false', 'south': 'false', 'up': 'true', 'down': 'false' } ] },
  { 'dungeons': [ 0x63, 0b0101 ], 'java': [ 'minecraft:brown_mushroom_block', { 'east': 'false', 'west': 'false', 'north': 'false', 'south': 'false', 'up': 'true', 'down': 'false' } ] },
  { 'dungeons': [ 0x63, 0b0110 ], 'java': [ 'minecraft:brown_mushroom_block', { 'east': 'true', 'west': 'false', 'north': 'false', 'south': 'false', 'up': 'true', 'down': 'false' } ] },
  { 'dungeons': [ 0x63, 0b0111 ], 'java': [ 'minecraft:brown_mushroom_block', { 'east': 'false', 'west': 'true', 'north': 'false', 'south': 'false', 'up': 'true', 'down': 'false' } ] },
  { 'dungeons': [ 0x63, 0b1000 ], 'java': [ 'minecraft:brown_mushroom_block', { 'east': 'false', 'west': 'false', 'north': 'false', 'south': 'true', 'up': 'true', 'down': 'false' } ] },
  { 'dungeons': [ 0x63, 0b1001 ], 'java': [ 'minecraft:brown_mushroom_block', { 'east': 'true', 'west': 'false', 'north': 'false', 'south': 'true', 'up': 'true', 'down': 'false' } ] },
  { 'dungeons': [ 0x63, 0b1010 ], 'java': [ 'minecraft:mushroom_stem', { 'east': 'true', 'west': 'true', 'north': 'true', 'south': 'true', 'up': 'false', 'down': 'false' } ] },
  { 'dungeons': [ 0x63, 0b1011 ], 'java': [ 'minecraft:brown_mushroom_block', { 'east': 'false', 'west': 'false', 'north': 'false', 'south': 'false', 'up': 'false', 'down': 'false' } ] },
  { 'dungeons': [ 0x63, 0b1100 ], 'java': [ 'minecraft:brown_mushroom_block', { 'east': 'false', 'west': 'false', 'north': 'false', 'south': 'false', 'up': 'false', 'down': 'false' } ] },
  { 'dungeons': [ 0x63, 0b1101 ], 'java': [ 'minecraft:brown_mushroom_block', { 'east': 'false', 'west': 'false', 'north': 'false', 'south': 'false', 'up': 'false', 'down': 'false' } ] },
  { 'dungeons': [ 0x63, 0b1110 ], 'java': [ 'minecraft:brown_mushroom_block', { 'east': 'true', 'west': 'true', 'north': 'true', 'south': 'true', 'up': 'true', 'down': 'true' } ] },
  { 'dungeons': [ 0x63, 0b1111 ], 'java': [ 'minecraft:mushroom_stem', { 'east': 'true', 'west': 'true', 'north': 'true', 'south': 'true', 'up': 'true', 'down': 'true' } ] },
  { 'dungeons': [ 0x64, 0b0000 ], 'java': [ 'minecraft:red_mushroom_block', { 'east': 'false', 'west': 'false', 'north': 'false', 'south': 'false', 'up': 'false', 'down': 'false' } ] },
  { 'dungeons': [ 0x64, 0b0001 ], 'java': [ 'minecraft:red_mushroom_block', { 'east': 'false', 'west': 'true', 'north': 'true', 'south': 'false', 'up': 'true', 'down': 'false' } ] },
  { 'dungeons': [ 0x64, 0b0010 ], 'java': [ 'minecraft:red_mushroom_block', { 'east': 'false', 'west': 'false', 'north': 'true', 'south': 'false', 'up': 'true', 'down': 'false' } ] },
  { 'dungeons': [ 0x64, 0b0011 ], 'java': [ 'minecraft:red_mushroom_block', { 'east': 'true', 'west': 'false', 'north': 'true', 'south': 'false', 'up': 'true', 'down': 'false' } ] },
  { 'dungeons': [ 0x64, 0b0100 ], 'java': [ 'minecraft:red_mushroom_block', { 'east': 'false', 'west': 'true', 'north': 'false', 'south': 'false', 'up': 'true', 'down': 'false' } ] },
  { 'dungeons': [ 0x64, 0b0101 ], 'java': [ 'minecraft:red_mushroom_block', { 'east': 'false', 'west': 'false', 'north': 'false', 'south': 'false', 'up': 'true', 'down': 'false' } ] },
  { 'dungeons': [ 0x64, 0b0110 ], 'java': [ 'minecraft:red_mushroom_block', { 'east': 'true', 'west': 'false', 'north': 'false', 'south': 'false', 'up': 'true', 'down': 'false' } ] },
  { 'dungeons': [ 0x64, 0b0111 ], 'java': [ 'minecraft:red_mushroom_block', { 'east': 'false', 'west': 'true', 'north': 'false', 'south': 'false', 'up': 'true', 'down': 'false' } ] },
  { 'dungeons': [ 0x64, 0b1000 ], 'java': [ 'minecraft:red_mushroom_block', { 'east': 'false', 'west': 'false', 'north': 'false', 'south': 'true', 'up': 'true', 'down': 'false' } ] },
  { 'dungeons': [ 0x64, 0b1001 ], 'java': [ 'minecraft:red_mushroom_block', { 'east': 'true', 'west': 'false', 'north': 'false', 'south': 'true', 'up': 'true', 'down': 'false' } ] },
  { 'dungeons': [ 0x64, 0b1010 ], 'java': [ 'minecraft:mushroom_stem', { 'east': 'true', 'west': 'true', 'north': 'true', 'south': 'true', 'up': 'false', 'down': 'false' } ] },
  { 'dungeons': [ 0x64, 0b1011 ], 'java': [ 'minecraft:red_mushroom_block', { 'east': 'false', 'west': 'false', 'north': 'false', 'south': 'false', 'up': 'false', 'down': 'false' } ] },
  { 'dungeons': [ 0x64, 0b1100 ], 'java': [ 'minecraft:red_mushroom_block', { 'east': 'false', 'west': 'false', 'north': 'false', 'south': 'false', 'up': 'false', 'down': 'false' } ] },
  { 'dungeons': [ 0x64, 0b1101 ], 'java': [ 'minecraft:red_mushroom_block', { 'east': 'false', 'west': 'false', 'north': 'false', 'south': 'false', 'up': 'false', 'down': 'false' } ] },
  { 'dungeons': [ 0x64, 0b1110 ], 'java': [ 'minecraft:red_mushroom_block', { 'east': 'true', 'west': 'true', 'north': 'true', 'south': 'true', 'up': 'true', 'down': 'true' } ] },
  { 'dungeons': [ 0x64, 0b1111 ], 'java': [ 'minecraft:mushroom_stem', { 'east': 'true', 'west': 'true', 'north': 'true', 'south': 'true', 'up': 'true', 'down': 'true' } ] },
  { 'dungeons': [ 0x65, 0b0000 ], 'java': [ 'minecraft:iron_bars' ] },
  { 'dungeons': [ 0x66, 0b0000 ], 'java': [ 'minecraft:glass_pane' ] },
  { 'dungeons': [ 0x67, 0b0000 ], 'java': [ 'minecraft:melon' ] },
  { 'dungeons': [ 0x68, 0b0000 ], 'java': [ 'minecraft:pumpkin_stem', { 'age': '0' } ] },
  { 'dungeons': [ 0x68, 0b0001 ], 'java': [ 'minecraft:pumpkin_stem', { 'age': '1' } ] },
  { 'dungeons': [ 0x68, 0b0010 ], 'java': [ 'minecraft:pumpkin_stem', { 'age': '2' } ] },
  { 'dungeons': [ 0x68, 0b0011 ], 'java': [ 'minecraft:pumpkin_stem', { 'age': '3' } ] },
  { 'dungeons': [ 0x68, 0b0100 ], 'java': [ 'minecraft:pumpkin_stem', { 'age': '4' } ] },
  { 'dungeons': [ 0x68, 0b0101 ], 'java': [ 'minecraft:pumpkin_stem', { 'age': '5' } ] },
  { 'dungeons': [ 0x68, 0b0110 ], 'java': [ 'minecraft:pumpkin_stem', { 'age': '6' } ] },
  { 'dungeons': [ 0x68, 0b0111 ], 'java': [ 'minecraft:pumpkin_stem', { 'age': '7' } ] },
  { 'dungeons': [ 0x69, 0b0000 ], 'java': [ 'minecraft:melon_stem', { 'age': '0' } ] },
  { 'dungeons': [ 0x69, 0b0001 ], 'java': [ 'minecraft:melon_stem', { 'age': '1' } ] },
  { 'dungeons': [ 0x69, 0b0010 ], 'java': [ 'minecraft:melon_stem', { 'age': '2' } ] },
  { 'dungeons': [ 0x69, 0b0011 ], 'java': [ 'minecraft:melon_stem', { 'age': '3' } ] },
  { 'dungeons': [ 0x69, 0b0100 ], 'java': [ 'minecraft:melon_stem', { 'age': '4' } ] },
  { 'dungeons': [ 0x69, 0b0101 ], 'java': [ 'minecraft:melon_stem', { 'age': '5' } ] },
  { 'dungeons': [ 0x69, 0b0110 ], 'java': [ 'minecraft:melon_stem', { 'age': '6' } ] },
  { 'dungeons': [ 0x69, 0b0111 ], 'java': [ 'minecraft:melon_stem', { 'age': '7' } ] },
  { 'dungeons': [ 0x6a, 0b0000 ], 'java': [ 'minecraft:vine', { 'east': 'false', 'north': 'false', 'west': 'false', 'south': 'false' } ] },
  { 'dungeons': [ 0x6a, 0b0001 ], 'java': [ 'minecraft:vine', { 'east': 'false', 'north': 'false', 'west': 'false', 'south': 'true' } ] },
  { 'dungeons': [ 0x6a, 0b0010 ], 'java': [ 'minecraft:vine', { 'east': 'false', 'north': 'false', 'west': 'true', 'south': 'false' } ] },
  { 'dungeons': [ 0x6a, 0b0011 ], 'java': [ 'minecraft:vine', { 'east': 'false', 'north': 'false', 'west': 'true', 'south': 'true' } ] },
  { 'dungeons': [ 0x6a, 0b0100 ], 'java': [ 'minecraft:vine', { 'east': 'false', 'north': 'true', 'west': 'false', 'south': 'false' } ] },
  { 'dungeons': [ 0x6a, 0b0101 ], 'java': [ 'minecraft:vine', { 'east': 'false', 'north': 'true', 'west': 'false', 'south': 'true' } ] },
  { 'dungeons': [ 0x6a, 0b0110 ], 'java': [ 'minecraft:vine', { 'east': 'false', 'north': 'true', 'west': 'true', 'south': 'false' } ] },
  { 'dungeons': [ 0x6a, 0b0111 ], 'java': [ 'minecraft:vine', { 'east': 'false', 'north': 'true', 'west': 'true', 'south': 'true' } ] },
  { 'dungeons': [ 0x6a, 0b1000 ], 'java': [ 'minecraft:vine', { 'east': 'true', 'north': 'false', 'west': 'false', 'south': 'false' } ] },
  { 'dungeons': [ 0x6a, 0b1001 ], 'java': [ 'minecraft:vine', { 'east': 'true', 'north': 'false', 'west': 'false', 'south': 'true' } ] },
  { 'dungeons': [ 0x6a, 0b1010 ], 'java': [ 'minecraft:vine', { 'east': 'true', 'north': 'false', 'west': 'true', 'south': 'false' } ] },
  { 'dungeons': [ 0x6a, 0b1011 ], 'java': [ 'minecraft:vine', { 'east': 'true', 'north': 'false', 'west': 'true', 'south': 'true' } ] },
  { 'dungeons': [ 0x6a, 0b1100 ], 'java': [ 'minecraft:vine', { 'east': 'true', 'north': 'true', 'west': 'false', 'south': 'false' } ] },
  { 'dungeons': [ 0x6a, 0b1101 ], 'java': [ 'minecraft:vine', { 'east': 'true', 'north': 'true', 'west': 'false', 'south': 'true' } ] },
  { 'dungeons': [ 0x6a, 0b1110 ], 'java': [ 'minecraft:vine', { 'east': 'true', 'north': 'true', 'west': 'true', 'south': 'false' } ] },
  { 'dungeons': [ 0x6a, 0b1111 ], 'java': [ 'minecraft:vine', { 'east': 'true', 'north': 'true', 'west': 'true', 'south': 'true' } ] },
  { 'dungeons': [ 0x6c, 0b0000 ], 'java': [ 'minecraft:brick_stairs', { 'facing': 'east', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x6c, 0b0001 ], 'java': [ 'minecraft:brick_stairs', { 'facing': 'west', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x6c, 0b0010 ], 'java': [ 'minecraft:brick_stairs', { 'facing': 'south', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x6c, 0b0011 ], 'java': [ 'minecraft:brick_stairs', { 'facing': 'north', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x6c, 0b0100 ], 'java': [ 'minecraft:brick_stairs', { 'facing': 'east', 'half': 'top' } ] },
  { 'dungeons': [ 0x6c, 0b0101 ], 'java': [ 'minecraft:brick_stairs', { 'facing': 'west', 'half': 'top' } ] },
  { 'dungeons': [ 0x6c, 0b0110 ], 'java': [ 'minecraft:brick_stairs', { 'facing': 'south', 'half': 'top' } ] },
  { 'dungeons': [ 0x6c, 0b0111 ], 'java': [ 'minecraft:brick_stairs', { 'facing': 'north', 'half': 'top' } ] },
  { 'dungeons': [ 0x6d, 0b0000 ], 'java': [ 'minecraft:stone_brick_stairs', { 'facing': 'east', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x6d, 0b0001 ], 'java': [ 'minecraft:stone_brick_stairs', { 'facing': 'west', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x6d, 0b0010 ], 'java': [ 'minecraft:stone_brick_stairs', { 'facing': 'south', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x6d, 0b0011 ], 'java': [ 'minecraft:stone_brick_stairs', { 'facing': 'north', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x6d, 0b0100 ], 'java': [ 'minecraft:stone_brick_stairs', { 'facing': 'east', 'half': 'top' } ] },
  { 'dungeons': [ 0x6d, 0b0101 ], 'java': [ 'minecraft:stone_brick_stairs', { 'facing': 'west', 'half': 'top' } ] },
  { 'dungeons': [ 0x6d, 0b0110 ], 'java': [ 'minecraft:stone_brick_stairs', { 'facing': 'south', 'half': 'top' } ] },
  { 'dungeons': [ 0x6d, 0b0111 ], 'java': [ 'minecraft:stone_brick_stairs', { 'facing': 'north', 'half': 'top' } ] },
  { 'dungeons': [ 0x6e, 0b0000 ], 'java': [ 'minecraft:podzol' ] }, # Out of bounds grass
  { 'dungeons': [ 0x6f, 0b0000 ], 'java': [ 'minecraft:lily_pad' ] },
  { 'dungeons': [ 0x70, 0b0000 ], 'java': [ 'minecraft:nether_bricks' ] },
  { 'dungeons': [ 0x71, 0b0000 ], 'java': [ 'minecraft:nether_brick_fence' ] },
  { 'dungeons': [ 0x72, 0b0000 ], 'java': [ 'minecraft:nether_brick_stairs', { 'facing': 'east', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x72, 0b0001 ], 'java': [ 'minecraft:nether_brick_stairs', { 'facing': 'west', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x72, 0b0010 ], 'java': [ 'minecraft:nether_brick_stairs', { 'facing': 'south', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x72, 0b0011 ], 'java': [ 'minecraft:nether_brick_stairs', { 'facing': 'north', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x72, 0b0100 ], 'java': [ 'minecraft:nether_brick_stairs', { 'facing': 'east', 'half': 'top' } ] },
  { 'dungeons': [ 0x72, 0b0101 ], 'java': [ 'minecraft:nether_brick_stairs', { 'facing': 'west', 'half': 'top' } ] },
  { 'dungeons': [ 0x72, 0b0110 ], 'java': [ 'minecraft:nether_brick_stairs', { 'facing': 'south', 'half': 'top' } ] },
  { 'dungeons': [ 0x72, 0b0111 ], 'java': [ 'minecraft:nether_brick_stairs', { 'facing': 'north', 'half': 'top' } ] },
  { 'dungeons': [ 0x74, 0b0000 ], 'java': [ 'minecraft:enchanting_table' ] },
  { 'dungeons': [ 0x75, 0b0000 ], 'java': [ 'minecraft:brewing_stand' ] },
  { 'dungeons': [ 0x76, 0b0000 ], 'java': [ 'minecraft:cauldron', { 'level': '0' } ] },
  { 'dungeons': [ 0x76, 0b0001 ], 'java': [ 'minecraft:cauldron', { 'level': '0' } ] },
  { 'dungeons': [ 0x76, 0b0010 ], 'java': [ 'minecraft:cauldron', { 'level': '1' } ] },
  { 'dungeons': [ 0x76, 0b0011 ], 'java': [ 'minecraft:cauldron', { 'level': '1' } ] },
  { 'dungeons': [ 0x76, 0b0100 ], 'java': [ 'minecraft:cauldron', { 'level': '2' } ] },
  { 'dungeons': [ 0x76, 0b0101 ], 'java': [ 'minecraft:cauldron', { 'level': '2' } ] },
  { 'dungeons': [ 0x76, 0b0110 ], 'java': [ 'minecraft:cauldron', { 'level': '3' } ] },
  { 'dungeons': [ 0x7b, 0b0000 ], 'java': [ 'minecraft:redstone_lamp' ] },
  { 'dungeons': [ 0x7d, 0b0000 ], 'java': [ 'minecraft:dropper', { 'triggered': 'false', 'facing': 'down' } ] },
  { 'dungeons': [ 0x7d, 0b0001 ], 'java': [ 'minecraft:dropper', { 'triggered': 'false', 'facing': 'up' } ] },
  { 'dungeons': [ 0x7d, 0b0010 ], 'java': [ 'minecraft:dropper', { 'triggered': 'false', 'facing': 'north' } ] },
  { 'dungeons': [ 0x7d, 0b0011 ], 'java': [ 'minecraft:dropper', { 'triggered': 'false', 'facing': 'south' } ] },
  { 'dungeons': [ 0x7d, 0b0100 ], 'java': [ 'minecraft:dropper', { 'triggered': 'false', 'facing': 'west' } ] },
  { 'dungeons': [ 0x7d, 0b0101 ], 'java': [ 'minecraft:dropper', { 'triggered': 'false', 'facing': 'east' } ] },
  { 'dungeons': [ 0x7d, 0b1000 ], 'java': [ 'minecraft:dropper', { 'triggered': 'true', 'facing': 'down' } ] },
  { 'dungeons': [ 0x7d, 0b1001 ], 'java': [ 'minecraft:dropper', { 'triggered': 'true', 'facing': 'up' } ] },
  { 'dungeons': [ 0x7d, 0b1010 ], 'java': [ 'minecraft:dropper', { 'triggered': 'true', 'facing': 'north' } ] },
  { 'dungeons': [ 0x7d, 0b1011 ], 'java': [ 'minecraft:dropper', { 'triggered': 'true', 'facing': 'south' } ] },
  { 'dungeons': [ 0x7d, 0b1100 ], 'java': [ 'minecraft:dropper', { 'triggered': 'true', 'facing': 'west' } ] },
  { 'dungeons': [ 0x7d, 0b1101 ], 'java': [ 'minecraft:dropper', { 'triggered': 'true', 'facing': 'east' } ] },
  { 'dungeons': [ 0x80, 0b0000 ], 'java': [ 'minecraft:sandstone_stairs', { 'facing': 'east', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x80, 0b0001 ], 'java': [ 'minecraft:sandstone_stairs', { 'facing': 'west', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x80, 0b0010 ], 'java': [ 'minecraft:sandstone_stairs', { 'facing': 'south', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x80, 0b0011 ], 'java': [ 'minecraft:sandstone_stairs', { 'facing': 'north', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x80, 0b0100 ], 'java': [ 'minecraft:sandstone_stairs', { 'facing': 'east', 'half': 'top' } ] },
  { 'dungeons': [ 0x80, 0b0101 ], 'java': [ 'minecraft:sandstone_stairs', { 'facing': 'west', 'half': 'top' } ] },
  { 'dungeons': [ 0x80, 0b0110 ], 'java': [ 'minecraft:sandstone_stairs', { 'facing': 'south', 'half': 'top' } ] },
  { 'dungeons': [ 0x80, 0b0111 ], 'java': [ 'minecraft:sandstone_stairs', { 'facing': 'north', 'half': 'top' } ] },
  { 'dungeons': [ 0x85, 0b0000 ], 'java': [ 'minecraft:emerald_block' ] },
  { 'dungeons': [ 0x86, 0b0000 ], 'java': [ 'minecraft:spruce_stairs', { 'facing': 'east', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x86, 0b0001 ], 'java': [ 'minecraft:spruce_stairs', { 'facing': 'west', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x86, 0b0010 ], 'java': [ 'minecraft:spruce_stairs', { 'facing': 'south', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x86, 0b0011 ], 'java': [ 'minecraft:spruce_stairs', { 'facing': 'north', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x86, 0b0100 ], 'java': [ 'minecraft:spruce_stairs', { 'facing': 'east', 'half': 'top' } ] },
  { 'dungeons': [ 0x86, 0b0101 ], 'java': [ 'minecraft:spruce_stairs', { 'facing': 'west', 'half': 'top' } ] },
  { 'dungeons': [ 0x86, 0b0110 ], 'java': [ 'minecraft:spruce_stairs', { 'facing': 'south', 'half': 'top' } ] },
  { 'dungeons': [ 0x86, 0b0111 ], 'java': [ 'minecraft:spruce_stairs', { 'facing': 'north', 'half': 'top' } ] },
  { 'dungeons': [ 0x87, 0b0000 ], 'java': [ 'minecraft:birch_stairs', { 'facing': 'east', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x87, 0b0001 ], 'java': [ 'minecraft:birch_stairs', { 'facing': 'west', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x87, 0b0010 ], 'java': [ 'minecraft:birch_stairs', { 'facing': 'south', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x87, 0b0011 ], 'java': [ 'minecraft:birch_stairs', { 'facing': 'north', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x87, 0b0100 ], 'java': [ 'minecraft:birch_stairs', { 'facing': 'east', 'half': 'top' } ] },
  { 'dungeons': [ 0x87, 0b0101 ], 'java': [ 'minecraft:birch_stairs', { 'facing': 'west', 'half': 'top' } ] },
  { 'dungeons': [ 0x87, 0b0110 ], 'java': [ 'minecraft:birch_stairs', { 'facing': 'south', 'half': 'top' } ] },
  { 'dungeons': [ 0x87, 0b0111 ], 'java': [ 'minecraft:birch_stairs', { 'facing': 'north', 'half': 'top' } ] },
  { 'dungeons': [ 0x88, 0b0000 ], 'java': [ 'minecraft:jungle_stairs', { 'facing': 'east', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x88, 0b0001 ], 'java': [ 'minecraft:jungle_stairs', { 'facing': 'west', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x88, 0b0010 ], 'java': [ 'minecraft:jungle_stairs', { 'facing': 'south', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x88, 0b0011 ], 'java': [ 'minecraft:jungle_stairs', { 'facing': 'north', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x88, 0b0100 ], 'java': [ 'minecraft:jungle_stairs', { 'facing': 'east', 'half': 'top' } ] },
  { 'dungeons': [ 0x88, 0b0101 ], 'java': [ 'minecraft:jungle_stairs', { 'facing': 'west', 'half': 'top' } ] },
  { 'dungeons': [ 0x88, 0b0110 ], 'java': [ 'minecraft:jungle_stairs', { 'facing': 'south', 'half': 'top' } ] },
  { 'dungeons': [ 0x88, 0b0111 ], 'java': [ 'minecraft:jungle_stairs', { 'facing': 'north', 'half': 'top' } ] },
  { 'dungeons': [ 0x89, 0b0000 ], 'java': [ 'minecraft:blackstone_slab', { 'type': 'bottom' } ] }, # stonefloor1 slab
  { 'dungeons': [ 0x89, 0b0001 ], 'java': [ 'minecraft:crimson_slab', { 'type': 'bottom' } ] }, # stonefloor2 slab
  { 'dungeons': [ 0x89, 0b0010 ], 'java': [ 'minecraft:polished_blackstone_slab', { 'type': 'bottom' } ] }, # stonefloor3 slab
  { 'dungeons': [ 0x89, 0b0011 ], 'java': [ 'minecraft:polished_blackstone_brick_slab', { 'type': 'bottom' } ] }, # stonefloor4 slab
  { 'dungeons': [ 0x89, 0b0100 ], 'java': [ 'minecraft:smooth_quartz_slab', { 'type': 'bottom' } ] }, # stonefloor5 slab
  { 'dungeons': [ 0x89, 0b0101 ], 'java': [ 'minecraft:stone_slab', { 'type': 'bottom' } ] }, # stonefloor6 slab
  { 'dungeons': [ 0x89, 0b0110 ], 'java': [ 'minecraft:smooth_sandstone_slab', { 'type': 'bottom' } ] }, # stonefloor7 slab
  { 'dungeons': [ 0x89, 0b0111 ], 'java': [ 'minecraft:cut_sandstone_slab', { 'type': 'bottom' } ] }, # stonefloor8 slab
  { 'dungeons': [ 0x89, 0b1000 ], 'java': [ 'minecraft:blackstone_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0x89, 0b1001 ], 'java': [ 'minecraft:crimson_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0x89, 0b1010 ], 'java': [ 'minecraft:polished_blackstone_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0x89, 0b1011 ], 'java': [ 'minecraft:polished_blackstone_brick_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0x89, 0b1100 ], 'java': [ 'minecraft:smooth_quartz_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0x89, 0b1101 ], 'java': [ 'minecraft:stone_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0x89, 0b1110 ], 'java': [ 'minecraft:smooth_sandstone_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0x89, 0b1111 ], 'java': [ 'minecraft:cut_sandstone_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0x8b, 0b0000 ], 'java': [ 'minecraft:cobblestone_wall' ] },
  { 'dungeons': [ 0x8b, 0b0001 ], 'java': [ 'minecraft:mossy_cobblestone_wall' ] },
  { 'dungeons': [ 0x8b, 0b0010 ], 'java': [ 'minecraft:granite_wall' ] },
  { 'dungeons': [ 0x8b, 0b0011 ], 'java': [ 'minecraft:diorite_wall' ] },
  { 'dungeons': [ 0x8b, 0b0100 ], 'java': [ 'minecraft:andesite_wall' ] },
  { 'dungeons': [ 0x8b, 0b0101 ], 'java': [ 'minecraft:sandstone_wall' ] },
  { 'dungeons': [ 0x8b, 0b0110 ], 'java': [ 'minecraft:brick_wall' ] },
  { 'dungeons': [ 0x8b, 0b0111 ], 'java': [ 'minecraft:stone_brick_wall' ] },
  { 'dungeons': [ 0x8b, 0b1000 ], 'java': [ 'minecraft:mossy_stone_brick_wall' ] },
  { 'dungeons': [ 0x8b, 0b1001 ], 'java': [ 'minecraft:end_stone_brick_wall' ] },
  { 'dungeons': [ 0x8b, 0b1010 ], 'java': [ 'minecraft:nether_brick_wall' ] },
  { 'dungeons': [ 0x8b, 0b1011 ], 'java': [ 'minecraft:prismarine_wall' ] },
  { 'dungeons': [ 0x8b, 0b1100 ], 'java': [ 'minecraft:red_sandstone_wall' ] },
  { 'dungeons': [ 0x8b, 0b1101 ], 'java': [ 'minecraft:red_nether_brick_wall' ] },
  { 'dungeons': [ 0x8d, 0b0000 ], 'java': [ 'minecraft:carrots', { 'age': '0' } ] },
  { 'dungeons': [ 0x8d, 0b0001 ], 'java': [ 'minecraft:carrots', { 'age': '1' } ] },
  { 'dungeons': [ 0x8d, 0b0010 ], 'java': [ 'minecraft:carrots', { 'age': '2' } ] },
  { 'dungeons': [ 0x8d, 0b0011 ], 'java': [ 'minecraft:carrots', { 'age': '3' } ] },
  { 'dungeons': [ 0x8d, 0b0100 ], 'java': [ 'minecraft:carrots', { 'age': '4' } ] },
  { 'dungeons': [ 0x8d, 0b0101 ], 'java': [ 'minecraft:carrots', { 'age': '5' } ] },
  { 'dungeons': [ 0x8d, 0b0110 ], 'java': [ 'minecraft:carrots', { 'age': '6' } ] },
  { 'dungeons': [ 0x8d, 0b0111 ], 'java': [ 'minecraft:carrots', { 'age': '7' } ] },
  { 'dungeons': [ 0x90, 0b0001 ], 'java': [ 'minecraft:skeleton_skull' ] },
  { 'dungeons': [ 0x90, 0b0010 ], 'java': [ 'minecraft:skeleton_wall_skull', { 'facing': 'north' } ] },
  { 'dungeons': [ 0x90, 0b0011 ], 'java': [ 'minecraft:skeleton_wall_skull', { 'facing': 'south' } ] },
  { 'dungeons': [ 0x90, 0b0100 ], 'java': [ 'minecraft:skeleton_wall_skull', { 'facing': 'east' } ] },
  { 'dungeons': [ 0x90, 0b0101 ], 'java': [ 'minecraft:skeleton_wall_skull', { 'facing': 'west' } ] },
  { 'dungeons': [ 0x91, 0b0000 ], 'java': [ 'minecraft:anvil', { 'facing': 'west' } ] },
  { 'dungeons': [ 0x91, 0b0001 ], 'java': [ 'minecraft:anvil', { 'facing': 'north' } ] },
  { 'dungeons': [ 0x91, 0b0010 ], 'java': [ 'minecraft:anvil', { 'facing': 'east' } ] },
  { 'dungeons': [ 0x91, 0b0011 ], 'java': [ 'minecraft:anvil', { 'facing': 'south' } ] },
  { 'dungeons': [ 0x91, 0b0100 ], 'java': [ 'minecraft:chipped_anvil', { 'facing': 'west' } ] },
  { 'dungeons': [ 0x91, 0b0101 ], 'java': [ 'minecraft:chipped_anvil', { 'facing': 'north' } ] },
  { 'dungeons': [ 0x91, 0b0110 ], 'java': [ 'minecraft:chipped_anvil', { 'facing': 'east' } ] },
  { 'dungeons': [ 0x91, 0b0111 ], 'java': [ 'minecraft:chipped_anvil', { 'facing': 'south' } ] },
  { 'dungeons': [ 0x91, 0b1000 ], 'java': [ 'minecraft:damaged_anvil', { 'facing': 'west' } ] },
  { 'dungeons': [ 0x91, 0b1001 ], 'java': [ 'minecraft:damaged_anvil', { 'facing': 'north' } ] },
  { 'dungeons': [ 0x91, 0b1010 ], 'java': [ 'minecraft:damaged_anvil', { 'facing': 'east' } ] },
  { 'dungeons': [ 0x91, 0b1011 ], 'java': [ 'minecraft:damaged_anvil', { 'facing': 'south' } ] },
  { 'dungeons': [ 0x98, 0b0000 ], 'java': [ 'minecraft:redstone_block' ] },
  { 'dungeons': [ 0x99, 0b0000 ], 'java': [ 'minecraft:quartz_ore' ] },
  { 'dungeons': [ 0x9b, 0b0000 ], 'java': [ 'minecraft:quartz_block' ] },
  { 'dungeons': [ 0x9b, 0b0001 ], 'java': [ 'minecraft:chiseled_quartz_block' ] },
  { 'dungeons': [ 0x9b, 0b0010 ], 'java': [ 'minecraft:quartz_pillar', { 'axis': 'y' } ] },
  { 'dungeons': [ 0x9b, 0b0011 ], 'java': [ 'minecraft:smooth_quartz' ] },
  { 'dungeons': [ 0x9b, 0b0100 ], 'java': [ 'minecraft:dead_fire_coral_block' ] },
  { 'dungeons': [ 0x9b, 0b0101 ], 'java': [ 'minecraft:dead_brain_coral_block' ] },
  { 'dungeons': [ 0x9b, 0b0110 ], 'java': [ 'minecraft:quartz_pillar', { 'axis': 'x' } ] },
  { 'dungeons': [ 0x9b, 0b1001 ], 'java': [ 'minecraft:dead_bubble_coral_block' ] },
  { 'dungeons': [ 0x9b, 0b1010 ], 'java': [ 'minecraft:quartz_pillar', { 'axis': 'z' } ] },
  { 'dungeons': [ 0x9c, 0b0000 ], 'java': [ 'minecraft:quartz_stairs', { 'facing': 'east', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x9c, 0b0001 ], 'java': [ 'minecraft:quartz_stairs', { 'facing': 'west', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x9c, 0b0010 ], 'java': [ 'minecraft:quartz_stairs', { 'facing': 'south', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x9c, 0b0011 ], 'java': [ 'minecraft:quartz_stairs', { 'facing': 'north', 'half': 'bottom' } ] },
  { 'dungeons': [ 0x9c, 0b0100 ], 'java': [ 'minecraft:quartz_stairs', { 'facing': 'east', 'half': 'top' } ] },
  { 'dungeons': [ 0x9c, 0b0101 ], 'java': [ 'minecraft:quartz_stairs', { 'facing': 'west', 'half': 'top' } ] },
  { 'dungeons': [ 0x9c, 0b0110 ], 'java': [ 'minecraft:quartz_stairs', { 'facing': 'south', 'half': 'top' } ] },
  { 'dungeons': [ 0x9c, 0b0111 ], 'java': [ 'minecraft:quartz_stairs', { 'facing': 'north', 'half': 'top' } ] },
  { 'dungeons': [ 0x9d, 0b0000, 0b0111 ], 'java': [ 'minecraft:oak_slab', { 'type': 'double' } ] },
  { 'dungeons': [ 0x9d, 0b0001, 0b0111 ], 'java': [ 'minecraft:spruce_slab', { 'type': 'double' } ] },
  { 'dungeons': [ 0x9d, 0b0010, 0b0111 ], 'java': [ 'minecraft:birch_slab', { 'type': 'double' } ] },
  { 'dungeons': [ 0x9d, 0b0011, 0b0111 ], 'java': [ 'minecraft:jungle_slab', { 'type': 'double' } ] },
  { 'dungeons': [ 0x9d, 0b0100, 0b0111 ], 'java': [ 'minecraft:acacia_slab', { 'type': 'double' } ] },
  { 'dungeons': [ 0x9d, 0b0101, 0b0111 ], 'java': [ 'minecraft:dark_oak_slab', { 'type': 'double' } ] },
  { 'dungeons': [ 0x9e, 0b0000 ], 'java': [ 'minecraft:oak_slab', { 'type': 'bottom' } ] },
  { 'dungeons': [ 0x9e, 0b0001 ], 'java': [ 'minecraft:spruce_slab', { 'type': 'bottom' } ] },
  { 'dungeons': [ 0x9e, 0b0010 ], 'java': [ 'minecraft:birch_slab', { 'type': 'bottom' } ] },
  { 'dungeons': [ 0x9e, 0b0011 ], 'java': [ 'minecraft:jungle_slab', { 'type': 'bottom' } ] },
  { 'dungeons': [ 0x9e, 0b0100 ], 'java': [ 'minecraft:acacia_slab', { 'type': 'bottom' } ] },
  { 'dungeons': [ 0x9e, 0b0101 ], 'java': [ 'minecraft:dark_oak_slab', { 'type': 'bottom' } ] },
  { 'dungeons': [ 0x9e, 0b1000 ], 'java': [ 'minecraft:oak_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0x9e, 0b1001 ], 'java': [ 'minecraft:spruce_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0x9e, 0b1010 ], 'java': [ 'minecraft:birch_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0x9e, 0b1011 ], 'java': [ 'minecraft:jungle_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0x9e, 0b1100 ], 'java': [ 'minecraft:acacia_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0x9e, 0b1101 ], 'java': [ 'minecraft:dark_oak_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0x9f, 0b0000 ], 'java': [ 'minecraft:white_terracotta' ] },
  { 'dungeons': [ 0x9f, 0b0001 ], 'java': [ 'minecraft:orange_terracotta' ] },
  { 'dungeons': [ 0x9f, 0b0010 ], 'java': [ 'minecraft:magenta_terracotta' ] },
  { 'dungeons': [ 0x9f, 0b0011 ], 'java': [ 'minecraft:light_blue_terracotta' ] },
  { 'dungeons': [ 0x9f, 0b0100 ], 'java': [ 'minecraft:yellow_terracotta' ] },
  { 'dungeons': [ 0x9f, 0b0101 ], 'java': [ 'minecraft:lime_terracotta' ] },
  { 'dungeons': [ 0x9f, 0b0110 ], 'java': [ 'minecraft:pink_terracotta' ] },
  { 'dungeons': [ 0x9f, 0b0111 ], 'java': [ 'minecraft:gray_terracotta' ] },
  { 'dungeons': [ 0x9f, 0b1000 ], 'java': [ 'minecraft:light_gray_terracotta' ] },
  { 'dungeons': [ 0x9f, 0b1001 ], 'java': [ 'minecraft:cyan_terracotta' ] },
  { 'dungeons': [ 0x9f, 0b1010 ], 'java': [ 'minecraft:purple_terracotta' ] },
  { 'dungeons': [ 0x9f, 0b1011 ], 'java': [ 'minecraft:blue_terracotta' ] },
  { 'dungeons': [ 0x9f, 0b1100 ], 'java': [ 'minecraft:brown_terracotta' ] },
  { 'dungeons': [ 0x9f, 0b1101 ], 'java': [ 'minecraft:green_terracotta' ] },
  { 'dungeons': [ 0x9f, 0b1110 ], 'java': [ 'minecraft:red_terracotta' ] },
  { 'dungeons': [ 0x9f, 0b1111 ], 'java': [ 'minecraft:black_terracotta' ] },
  { 'dungeons': [ 0xa1, 0b0000, 0b0111 ], 'java': [ 'minecraft:acacia_leaves', { 'persistent': 'false' } ] },
  { 'dungeons': [ 0xa1, 0b0001, 0b0111 ], 'java': [ 'minecraft:dark_oak_leaves', { 'persistent': 'false' } ] },
  { 'dungeons': [ 0xa1, 0b0100, 0b0111 ], 'java': [ 'minecraft:acacia_leaves', { 'persistent': 'true' } ] },
  { 'dungeons': [ 0xa1, 0b0101, 0b0111 ], 'java': [ 'minecraft:dark_oak_leaves', { 'persistent': 'true' } ] },
  { 'dungeons': [ 0xa2, 0b0000 ], 'java': [ 'minecraft:acacia_log', { 'axis': 'y' } ] },
  { 'dungeons': [ 0xa2, 0b0001 ], 'java': [ 'minecraft:dark_oak_log', { 'axis': 'y' } ] },
  { 'dungeons': [ 0xa2, 0b0100 ], 'java': [ 'minecraft:acacia_log', { 'axis': 'x' } ] },
  { 'dungeons': [ 0xa2, 0b0101 ], 'java': [ 'minecraft:dark_oak_log', { 'axis': 'x' } ] },
  { 'dungeons': [ 0xa2, 0b1000 ], 'java': [ 'minecraft:acacia_log', { 'axis': 'z' } ] },
  { 'dungeons': [ 0xa2, 0b1001 ], 'java': [ 'minecraft:dark_oak_log', { 'axis': 'z' } ] },
  { 'dungeons': [ 0xa2, 0b1100 ], 'java': [ 'minecraft:acacia_wood' ] },
  { 'dungeons': [ 0xa2, 0b1101 ], 'java': [ 'minecraft:dark_oak_wood' ] },
  { 'dungeons': [ 0xa3, 0b0000 ], 'java': [ 'minecraft:acacia_stairs', { 'facing': 'east', 'half': 'bottom' } ] },
  { 'dungeons': [ 0xa3, 0b0001 ], 'java': [ 'minecraft:acacia_stairs', { 'facing': 'west', 'half': 'bottom' } ] },
  { 'dungeons': [ 0xa3, 0b0010 ], 'java': [ 'minecraft:acacia_stairs', { 'facing': 'south', 'half': 'bottom' } ] },
  { 'dungeons': [ 0xa3, 0b0011 ], 'java': [ 'minecraft:acacia_stairs', { 'facing': 'north', 'half': 'bottom' } ] },
  { 'dungeons': [ 0xa3, 0b0100 ], 'java': [ 'minecraft:acacia_stairs', { 'facing': 'east', 'half': 'top' } ] },
  { 'dungeons': [ 0xa3, 0b0101 ], 'java': [ 'minecraft:acacia_stairs', { 'facing': 'west', 'half': 'top' } ] },
  { 'dungeons': [ 0xa3, 0b0110 ], 'java': [ 'minecraft:acacia_stairs', { 'facing': 'south', 'half': 'top' } ] },
  { 'dungeons': [ 0xa3, 0b0111 ], 'java': [ 'minecraft:acacia_stairs', { 'facing': 'north', 'half': 'top' } ] },
  { 'dungeons': [ 0xa4, 0b0000 ], 'java': [ 'minecraft:dark_oak_stairs', { 'facing': 'east', 'half': 'bottom' } ] },
  { 'dungeons': [ 0xa4, 0b0001 ], 'java': [ 'minecraft:dark_oak_stairs', { 'facing': 'west', 'half': 'bottom' } ] },
  { 'dungeons': [ 0xa4, 0b0010 ], 'java': [ 'minecraft:dark_oak_stairs', { 'facing': 'south', 'half': 'bottom' } ] },
  { 'dungeons': [ 0xa4, 0b0011 ], 'java': [ 'minecraft:dark_oak_stairs', { 'facing': 'north', 'half': 'bottom' } ] },
  { 'dungeons': [ 0xa4, 0b0100 ], 'java': [ 'minecraft:dark_oak_stairs', { 'facing': 'east', 'half': 'top' } ] },
  { 'dungeons': [ 0xa4, 0b0101 ], 'java': [ 'minecraft:dark_oak_stairs', { 'facing': 'west', 'half': 'top' } ] },
  { 'dungeons': [ 0xa4, 0b0110 ], 'java': [ 'minecraft:dark_oak_stairs', { 'facing': 'south', 'half': 'top' } ] },
  { 'dungeons': [ 0xa4, 0b0111 ], 'java': [ 'minecraft:dark_oak_stairs', { 'facing': 'north', 'half': 'top' } ] },
  { 'dungeons': [ 0xa7, 0b0000 ], 'java': [ 'minecraft:iron_trapdoor', { 'open': 'false', 'half': 'bottom', 'facing': 'east' } ] },
  { 'dungeons': [ 0xa7, 0b0001 ], 'java': [ 'minecraft:iron_trapdoor', { 'open': 'false', 'half': 'bottom', 'facing': 'west' } ] },
  { 'dungeons': [ 0xa7, 0b0010 ], 'java': [ 'minecraft:iron_trapdoor', { 'open': 'false', 'half': 'bottom', 'facing': 'south' } ] },
  { 'dungeons': [ 0xa7, 0b0011 ], 'java': [ 'minecraft:iron_trapdoor', { 'open': 'false', 'half': 'bottom', 'facing': 'north' } ] },
  { 'dungeons': [ 0xa7, 0b0100 ], 'java': [ 'minecraft:iron_trapdoor', { 'open': 'false', 'half': 'top', 'facing': 'east' } ] },
  { 'dungeons': [ 0xa7, 0b0101 ], 'java': [ 'minecraft:iron_trapdoor', { 'open': 'false', 'half': 'top', 'facing': 'west' } ] },
  { 'dungeons': [ 0xa7, 0b0110 ], 'java': [ 'minecraft:iron_trapdoor', { 'open': 'false', 'half': 'top', 'facing': 'south' } ] },
  { 'dungeons': [ 0xa7, 0b0111 ], 'java': [ 'minecraft:iron_trapdoor', { 'open': 'false', 'half': 'top', 'facing': 'north' } ] },
  { 'dungeons': [ 0xa7, 0b1000 ], 'java': [ 'minecraft:iron_trapdoor', { 'open': 'true', 'half': 'bottom', 'facing': 'east' } ] },
  { 'dungeons': [ 0xa7, 0b1001 ], 'java': [ 'minecraft:iron_trapdoor', { 'open': 'true', 'half': 'bottom', 'facing': 'west' } ] },
  { 'dungeons': [ 0xa7, 0b1010 ], 'java': [ 'minecraft:iron_trapdoor', { 'open': 'true', 'half': 'bottom', 'facing': 'south' } ] },
  { 'dungeons': [ 0xa7, 0b1011 ], 'java': [ 'minecraft:iron_trapdoor', { 'open': 'true', 'half': 'bottom', 'facing': 'north' } ] },
  { 'dungeons': [ 0xa7, 0b1100 ], 'java': [ 'minecraft:iron_trapdoor', { 'open': 'true', 'half': 'top', 'facing': 'east' } ] },
  { 'dungeons': [ 0xa7, 0b1101 ], 'java': [ 'minecraft:iron_trapdoor', { 'open': 'true', 'half': 'top', 'facing': 'west' } ] },
  { 'dungeons': [ 0xa7, 0b1110 ], 'java': [ 'minecraft:iron_trapdoor', { 'open': 'true', 'half': 'top', 'facing': 'south' } ] },
  { 'dungeons': [ 0xa7, 0b1111 ], 'java': [ 'minecraft:iron_trapdoor', { 'open': 'true', 'half': 'top', 'facing': 'north' } ] },
  { 'dungeons': [ 0xaa, 0b0000 ], 'java': [ 'minecraft:hay_block' ] },
  { 'dungeons': [ 0xab, 0b0000 ], 'java': [ 'minecraft:white_carpet' ] },
  { 'dungeons': [ 0xab, 0b0001 ], 'java': [ 'minecraft:orange_carpet' ] },
  { 'dungeons': [ 0xab, 0b0010 ], 'java': [ 'minecraft:magenta_carpet' ] },
  { 'dungeons': [ 0xab, 0b0011 ], 'java': [ 'minecraft:light_blue_carpet' ] },
  { 'dungeons': [ 0xab, 0b0100 ], 'java': [ 'minecraft:yellow_carpet' ] },
  { 'dungeons': [ 0xab, 0b0101 ], 'java': [ 'minecraft:lime_carpet' ] },
  { 'dungeons': [ 0xab, 0b0110 ], 'java': [ 'minecraft:pink_carpet' ] },
  { 'dungeons': [ 0xab, 0b0111 ], 'java': [ 'minecraft:gray_carpet' ] },
  { 'dungeons': [ 0xab, 0b1000 ], 'java': [ 'minecraft:light_gray_carpet' ] },
  { 'dungeons': [ 0xab, 0b1001 ], 'java': [ 'minecraft:cyan_carpet' ] },
  { 'dungeons': [ 0xab, 0b1010 ], 'java': [ 'minecraft:purple_carpet' ] },
  { 'dungeons': [ 0xab, 0b1011 ], 'java': [ 'minecraft:blue_carpet' ] },
  { 'dungeons': [ 0xab, 0b1100 ], 'java': [ 'minecraft:brown_carpet' ] },
  { 'dungeons': [ 0xab, 0b1101 ], 'java': [ 'minecraft:green_carpet' ] },
  { 'dungeons': [ 0xab, 0b1110 ], 'java': [ 'minecraft:red_carpet' ] },
  { 'dungeons': [ 0xab, 0b1111 ], 'java': [ 'minecraft:black_carpet' ] },
  { 'dungeons': [ 0xac, 0b0000 ], 'java': [ 'minecraft:terracotta' ] },
  { 'dungeons': [ 0xad, 0b0000 ], 'java': [ 'minecraft:coal_block' ] },
  { 'dungeons': [ 0xae, 0b0000 ], 'java': [ 'minecraft:packed_ice' ] },
  { 'dungeons': [ 0xaf, 0b0000 ], 'java': [ 'minecraft:sunflower', { 'half': 'lower' } ] },
  { 'dungeons': [ 0xaf, 0b0001 ], 'java': [ 'minecraft:lilac', { 'half': 'lower' } ] },
  { 'dungeons': [ 0xaf, 0b0010 ], 'java': [ 'minecraft:tall_grass', { 'half': 'lower' } ] },
  { 'dungeons': [ 0xaf, 0b0011 ], 'java': [ 'minecraft:large_fern', { 'half': 'lower' } ] },
  { 'dungeons': [ 0xaf, 0b0100 ], 'java': [ 'minecraft:rose_bush', { 'half': 'lower' } ] },
  { 'dungeons': [ 0xaf, 0b0101 ], 'java': [ 'minecraft:peony', { 'half': 'lower' } ] },
  { 'dungeons': [ 0xaf, 0b1000 ], 'java': [ 'minecraft:sunflower', { 'half': 'upper' } ] },
  { 'dungeons': [ 0xaf, 0b1001 ], 'java': [ 'minecraft:lilac', { 'half': 'upper' } ] },
  { 'dungeons': [ 0xaf, 0b1010 ], 'java': [ 'minecraft:tall_grass', { 'half': 'upper' } ] },
  { 'dungeons': [ 0xaf, 0b1011 ], 'java': [ 'minecraft:large_fern', { 'half': 'upper' } ] },
  { 'dungeons': [ 0xaf, 0b1100 ], 'java': [ 'minecraft:rose_bush', { 'half': 'upper' } ] },
  { 'dungeons': [ 0xaf, 0b1101 ], 'java': [ 'minecraft:peony', { 'half': 'upper' } ] },
  { 'dungeons': [ 0xb3, 0b0000 ], 'java': [ 'minecraft:red_sandstone' ] },
  { 'dungeons': [ 0xb3, 0b0001 ], 'java': [ 'minecraft:chiseled_red_sandstone' ] },
  { 'dungeons': [ 0xb3, 0b0010 ], 'java': [ 'minecraft:cut_red_sandstone' ] },
  { 'dungeons': [ 0xb3, 0b0011 ], 'java': [ 'minecraft:smooth_red_sandstone' ] },
  { 'dungeons': [ 0xb4, 0b0000 ], 'java': [ 'minecraft:red_sandstone_stairs', { 'facing': 'east', 'half': 'bottom' } ] },
  { 'dungeons': [ 0xb4, 0b0001 ], 'java': [ 'minecraft:red_sandstone_stairs', { 'facing': 'west', 'half': 'bottom' } ] },
  { 'dungeons': [ 0xb4, 0b0010 ], 'java': [ 'minecraft:red_sandstone_stairs', { 'facing': 'south', 'half': 'bottom' } ] },
  { 'dungeons': [ 0xb4, 0b0011 ], 'java': [ 'minecraft:red_sandstone_stairs', { 'facing': 'north', 'half': 'bottom' } ] },
  { 'dungeons': [ 0xb4, 0b0100 ], 'java': [ 'minecraft:red_sandstone_stairs', { 'facing': 'east', 'half': 'top' } ] },
  { 'dungeons': [ 0xb4, 0b0101 ], 'java': [ 'minecraft:red_sandstone_stairs', { 'facing': 'west', 'half': 'top' } ] },
  { 'dungeons': [ 0xb4, 0b0110 ], 'java': [ 'minecraft:red_sandstone_stairs', { 'facing': 'south', 'half': 'top' } ] },
  { 'dungeons': [ 0xb4, 0b0111 ], 'java': [ 'minecraft:red_sandstone_stairs', { 'facing': 'north', 'half': 'top' } ] },
  { 'dungeons': [ 0xb5, 0b0000 ], 'java': [ 'minecraft:red_sandstone_slab', { 'type': 'double' } ] },
  { 'dungeons': [ 0xb5, 0b0001 ], 'java': [ 'minecraft:purpur_slab', { 'type': 'double' } ] },
  { 'dungeons': [ 0xb5, 0b0010 ], 'java': [ 'minecraft:prismarine_slab', { 'type': 'double' } ] },
  { 'dungeons': [ 0xb5, 0b0011 ], 'java': [ 'minecraft:prismarine_brick_slab', { 'type': 'double' } ] },
  { 'dungeons': [ 0xb5, 0b0100 ], 'java': [ 'minecraft:dark_prismarine_slab', { 'type': 'double' } ] },
  { 'dungeons': [ 0xb5, 0b0101 ], 'java': [ 'minecraft:mossy_cobblestone_slab', { 'type': 'double' } ] },
  { 'dungeons': [ 0xb5, 0b0110 ], 'java': [ 'minecraft:smooth_sandstone_slab', { 'type': 'double' } ] },
  { 'dungeons': [ 0xb5, 0b0111 ], 'java': [ 'minecraft:red_nether_brick_slab', { 'type': 'double' } ] },
  { 'dungeons': [ 0xb6, 0b0000 ], 'java': [ 'minecraft:red_sandstone_slab', { 'type': 'bottom' } ] },
  { 'dungeons': [ 0xb6, 0b0001 ], 'java': [ 'minecraft:purpur_slab', { 'type': 'bottom' } ] },
  { 'dungeons': [ 0xb6, 0b0010 ], 'java': [ 'minecraft:prismarine_slab', { 'type': 'bottom' } ] },
  { 'dungeons': [ 0xb6, 0b0011 ], 'java': [ 'minecraft:prismarine_brick_slab', { 'type': 'bottom' } ] },
  { 'dungeons': [ 0xb6, 0b0100 ], 'java': [ 'minecraft:dark_prismarine_slab', { 'type': 'bottom' } ] },
  { 'dungeons': [ 0xb6, 0b0101 ], 'java': [ 'minecraft:mossy_cobblestone_slab', { 'type': 'bottom' } ] },
  { 'dungeons': [ 0xb6, 0b0110 ], 'java': [ 'minecraft:smooth_sandstone_slab', { 'type': 'bottom' } ] },
  { 'dungeons': [ 0xb6, 0b0111 ], 'java': [ 'minecraft:red_nether_brick_slab', { 'type': 'bottom' } ] },
  { 'dungeons': [ 0xb6, 0b1000 ], 'java': [ 'minecraft:red_sandstone_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0xb6, 0b1001 ], 'java': [ 'minecraft:purpur_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0xb6, 0b1010 ], 'java': [ 'minecraft:prismarine_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0xb6, 0b1011 ], 'java': [ 'minecraft:prismarine_brick_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0xb6, 0b1100 ], 'java': [ 'minecraft:dark_prismarine_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0xb6, 0b1101 ], 'java': [ 'minecraft:mossy_cobblestone_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0xb6, 0b1110 ], 'java': [ 'minecraft:smooth_sandstone_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0xb6, 0b1111 ], 'java': [ 'minecraft:red_nether_brick_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0xb6, 0b1000 ], 'java': [ 'minecraft:red_sandstone_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0xb6, 0b1001 ], 'java': [ 'minecraft:purpur_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0xb6, 0b1010 ], 'java': [ 'minecraft:prismarine_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0xb6, 0b1011 ], 'java': [ 'minecraft:prismarine_brick_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0xb6, 0b1100 ], 'java': [ 'minecraft:dark_prismarine_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0xb6, 0b1101 ], 'java': [ 'minecraft:mossy_cobblestone_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0xb6, 0b1110 ], 'java': [ 'minecraft:smooth_sandstone_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0xb6, 0b1111 ], 'java': [ 'minecraft:red_nether_brick_slab', { 'type': 'top' } ] },
  { 'dungeons': [ 0xb7, 0b0000 ], 'java': [ 'minecraft:spruce_fence_gate', { 'in_wall': 'false', 'open': 'false', 'facing': 'south' } ] },
  { 'dungeons': [ 0xb7, 0b0001 ], 'java': [ 'minecraft:spruce_fence_gate', { 'in_wall': 'false', 'open': 'false', 'facing': 'west' } ] },
  { 'dungeons': [ 0xb7, 0b0010 ], 'java': [ 'minecraft:spruce_fence_gate', { 'in_wall': 'false', 'open': 'false', 'facing': 'north' } ] },
  { 'dungeons': [ 0xb7, 0b0011 ], 'java': [ 'minecraft:spruce_fence_gate', { 'in_wall': 'false', 'open': 'false', 'facing': 'east' } ] },
  { 'dungeons': [ 0xb7, 0b0100 ], 'java': [ 'minecraft:spruce_fence_gate', { 'in_wall': 'false', 'open': 'true', 'facing': 'south' } ] },
  { 'dungeons': [ 0xb7, 0b0101 ], 'java': [ 'minecraft:spruce_fence_gate', { 'in_wall': 'false', 'open': 'true', 'facing': 'west' } ] },
  { 'dungeons': [ 0xb7, 0b0110 ], 'java': [ 'minecraft:spruce_fence_gate', { 'in_wall': 'false', 'open': 'true', 'facing': 'north' } ] },
  { 'dungeons': [ 0xb7, 0b0111 ], 'java': [ 'minecraft:spruce_fence_gate', { 'in_wall': 'false', 'open': 'true', 'facing': 'east' } ] },
  { 'dungeons': [ 0xb7, 0b1000 ], 'java': [ 'minecraft:spruce_fence_gate', { 'in_wall': 'true', 'open': 'false', 'facing': 'south' } ] },
  { 'dungeons': [ 0xb7, 0b1001 ], 'java': [ 'minecraft:spruce_fence_gate', { 'in_wall': 'true', 'open': 'false', 'facing': 'west' } ] },
  { 'dungeons': [ 0xb7, 0b1010 ], 'java': [ 'minecraft:spruce_fence_gate', { 'in_wall': 'true', 'open': 'false', 'facing': 'north' } ] },
  { 'dungeons': [ 0xb7, 0b1011 ], 'java': [ 'minecraft:spruce_fence_gate', { 'in_wall': 'true', 'open': 'false', 'facing': 'east' } ] },
  { 'dungeons': [ 0xb7, 0b1100 ], 'java': [ 'minecraft:spruce_fence_gate', { 'in_wall': 'true', 'open': 'true', 'facing': 'south' } ] },
  { 'dungeons': [ 0xb7, 0b1101 ], 'java': [ 'minecraft:spruce_fence_gate', { 'in_wall': 'true', 'open': 'true', 'facing': 'west' } ] },
  { 'dungeons': [ 0xb7, 0b1110 ], 'java': [ 'minecraft:spruce_fence_gate', { 'in_wall': 'true', 'open': 'true', 'facing': 'north' } ] },
  { 'dungeons': [ 0xb7, 0b1111 ], 'java': [ 'minecraft:spruce_fence_gate', { 'in_wall': 'true', 'open': 'true', 'facing': 'east' } ] },
  { 'dungeons': [ 0xbb, 0b0000 ], 'java': [ 'minecraft:acacia_fence_gate', { 'in_wall': 'false', 'open': 'false', 'facing': 'south' } ] },
  { 'dungeons': [ 0xbb, 0b0001 ], 'java': [ 'minecraft:acacia_fence_gate', { 'in_wall': 'false', 'open': 'false', 'facing': 'west' } ] },
  { 'dungeons': [ 0xbb, 0b0010 ], 'java': [ 'minecraft:acacia_fence_gate', { 'in_wall': 'false', 'open': 'false', 'facing': 'north' } ] },
  { 'dungeons': [ 0xbb, 0b0011 ], 'java': [ 'minecraft:acacia_fence_gate', { 'in_wall': 'false', 'open': 'false', 'facing': 'east' } ] },
  { 'dungeons': [ 0xbb, 0b0100 ], 'java': [ 'minecraft:acacia_fence_gate', { 'in_wall': 'false', 'open': 'true', 'facing': 'south' } ] },
  { 'dungeons': [ 0xbb, 0b0101 ], 'java': [ 'minecraft:acacia_fence_gate', { 'in_wall': 'false', 'open': 'true', 'facing': 'west' } ] },
  { 'dungeons': [ 0xbb, 0b0110 ], 'java': [ 'minecraft:acacia_fence_gate', { 'in_wall': 'false', 'open': 'true', 'facing': 'north' } ] },
  { 'dungeons': [ 0xbb, 0b0111 ], 'java': [ 'minecraft:acacia_fence_gate', { 'in_wall': 'false', 'open': 'true', 'facing': 'east' } ] },
  { 'dungeons': [ 0xbb, 0b1000 ], 'java': [ 'minecraft:acacia_fence_gate', { 'in_wall': 'true', 'open': 'false', 'facing': 'south' } ] },
  { 'dungeons': [ 0xbb, 0b1001 ], 'java': [ 'minecraft:acacia_fence_gate', { 'in_wall': 'true', 'open': 'false', 'facing': 'west' } ] },
  { 'dungeons': [ 0xbb, 0b1010 ], 'java': [ 'minecraft:acacia_fence_gate', { 'in_wall': 'true', 'open': 'false', 'facing': 'north' } ] },
  { 'dungeons': [ 0xbb, 0b1011 ], 'java': [ 'minecraft:acacia_fence_gate', { 'in_wall': 'true', 'open': 'false', 'facing': 'east' } ] },
  { 'dungeons': [ 0xbb, 0b1100 ], 'java': [ 'minecraft:acacia_fence_gate', { 'in_wall': 'true', 'open': 'true', 'facing': 'south' } ] },
  { 'dungeons': [ 0xbb, 0b1101 ], 'java': [ 'minecraft:acacia_fence_gate', { 'in_wall': 'true', 'open': 'true', 'facing': 'west' } ] },
  { 'dungeons': [ 0xbb, 0b1110 ], 'java': [ 'minecraft:acacia_fence_gate', { 'in_wall': 'true', 'open': 'true', 'facing': 'north' } ] },
  { 'dungeons': [ 0xbb, 0b1111 ], 'java': [ 'minecraft:acacia_fence_gate', { 'in_wall': 'true', 'open': 'true', 'facing': 'east' } ] },
  { 'dungeons': [ 0xc1, 0b0000 ], 'java': [ 'minecraft:spruce_door', { 'half': 'lower', 'open': 'false', 'facing': 'east' } ] },
  { 'dungeons': [ 0xc1, 0b0001 ], 'java': [ 'minecraft:spruce_door', { 'half': 'lower', 'open': 'false', 'facing': 'south' } ] },
  { 'dungeons': [ 0xc1, 0b0010 ], 'java': [ 'minecraft:spruce_door', { 'half': 'lower', 'open': 'false', 'facing': 'west' } ] },
  { 'dungeons': [ 0xc1, 0b0011 ], 'java': [ 'minecraft:spruce_door', { 'half': 'lower', 'open': 'false', 'facing': 'north' } ] },
  { 'dungeons': [ 0xc1, 0b0100 ], 'java': [ 'minecraft:spruce_door', { 'half': 'lower', 'open': 'true', 'facing': 'east' } ] },
  { 'dungeons': [ 0xc1, 0b0101 ], 'java': [ 'minecraft:spruce_door', { 'half': 'lower', 'open': 'true', 'facing': 'south' } ] },
  { 'dungeons': [ 0xc1, 0b0110 ], 'java': [ 'minecraft:spruce_door', { 'half': 'lower', 'open': 'true', 'facing': 'west' } ] },
  { 'dungeons': [ 0xc1, 0b0111 ], 'java': [ 'minecraft:spruce_door', { 'half': 'lower', 'open': 'true', 'facing': 'north' } ] },
  { 'dungeons': [ 0xc1, 0b1000 ], 'java': [ 'minecraft:spruce_door', { 'half': 'upper', 'powered': 'false', 'hinge': 'left' } ] },
  { 'dungeons': [ 0xc1, 0b1001 ], 'java': [ 'minecraft:spruce_door', { 'half': 'upper', 'powered': 'false', 'hinge': 'right' } ] },
  { 'dungeons': [ 0xc1, 0b1010 ], 'java': [ 'minecraft:spruce_door', { 'half': 'upper', 'powered': 'true', 'hinge': 'left' } ] },
  { 'dungeons': [ 0xc1, 0b1011 ], 'java': [ 'minecraft:spruce_door', { 'half': 'upper', 'powered': 'true', 'hinge': 'right' } ] },
  { 'dungeons': [ 0xc5, 0b0000 ], 'java': [ 'minecraft:dark_oak_door', { 'half': 'lower', 'open': 'false', 'facing': 'east' } ] },
  { 'dungeons': [ 0xc5, 0b0001 ], 'java': [ 'minecraft:dark_oak_door', { 'half': 'lower', 'open': 'false', 'facing': 'south' } ] },
  { 'dungeons': [ 0xc5, 0b0010 ], 'java': [ 'minecraft:dark_oak_door', { 'half': 'lower', 'open': 'false', 'facing': 'west' } ] },
  { 'dungeons': [ 0xc5, 0b0011 ], 'java': [ 'minecraft:dark_oak_door', { 'half': 'lower', 'open': 'false', 'facing': 'north' } ] },
  { 'dungeons': [ 0xc5, 0b0100 ], 'java': [ 'minecraft:dark_oak_door', { 'half': 'lower', 'open': 'true', 'facing': 'east' } ] },
  { 'dungeons': [ 0xc5, 0b0101 ], 'java': [ 'minecraft:dark_oak_door', { 'half': 'lower', 'open': 'true', 'facing': 'south' } ] },
  { 'dungeons': [ 0xc5, 0b0110 ], 'java': [ 'minecraft:dark_oak_door', { 'half': 'lower', 'open': 'true', 'facing': 'west' } ] },
  { 'dungeons': [ 0xc5, 0b0111 ], 'java': [ 'minecraft:dark_oak_door', { 'half': 'lower', 'open': 'true', 'facing': 'north' } ] },
  { 'dungeons': [ 0xc5, 0b1000 ], 'java': [ 'minecraft:dark_oak_door', { 'half': 'upper', 'powered': 'false', 'hinge': 'left' } ] },
  { 'dungeons': [ 0xc5, 0b1001 ], 'java': [ 'minecraft:dark_oak_door', { 'half': 'upper', 'powered': 'false', 'hinge': 'right' } ] },
  { 'dungeons': [ 0xc5, 0b1010 ], 'java': [ 'minecraft:dark_oak_door', { 'half': 'upper', 'powered': 'true', 'hinge': 'left' } ] },
  { 'dungeons': [ 0xc5, 0b1011 ], 'java': [ 'minecraft:dark_oak_door', { 'half': 'upper', 'powered': 'true', 'hinge': 'right' } ] },
  { 'dungeons': [ 0xc6, 0b0000 ], 'java': [ 'minecraft:grass_path' ] },
  { 'dungeons': [ 0xc6, 0b0001 ], 'java': [ 'minecraft:farmland', { 'moisture': '1' } ] }, # dirt_path
  { 'dungeons': [ 0xc6, 0b0010 ], 'java': [ 'minecraft:farmland', { 'moisture': '2' } ] }, # stone_path
  { 'dungeons': [ 0xc6, 0b0011 ], 'java': [ 'minecraft:farmland', { 'moisture': '3' } ] }, # skull_path
  { 'dungeons': [ 0xc6, 0b0100 ], 'java': [ 'minecraft:farmland', { 'moisture': '4' } ] }, # gravel_path
  { 'dungeons': [ 0xc7, 0b0011 ], 'java': [ 'minecraft:dead_tube_coral_block' ] },
  { 'dungeons': [ 0xe0, 0b0000 ], 'java': [ 'minecraft:white_concrete' ] }, # custom_0
  { 'dungeons': [ 0xe1, 0b0000 ], 'java': [ 'minecraft:orange_concrete' ] }, # custom_1
  { 'dungeons': [ 0xe2, 0b0000 ], 'java': [ 'minecraft:magenta_concrete' ] }, # custom_2
  { 'dungeons': [ 0xe3, 0b0000 ], 'java': [ 'minecraft:light_blue_concrete' ] }, # custom_3
  { 'dungeons': [ 0xe4, 0b0000 ], 'java': [ 'minecraft:yellow_concrete' ] }, # custom_4
  { 'dungeons': [ 0xe5, 0b0000 ], 'java': [ 'minecraft:lime_concrete' ] }, # custom_5
  { 'dungeons': [ 0xe6, 0b0000 ], 'java': [ 'minecraft:pink_concrete' ] }, # custom_6
  { 'dungeons': [ 0xe7, 0b0000 ], 'java': [ 'minecraft:gray_concrete' ] }, # custom_7
  { 'dungeons': [ 0xe8, 0b0000 ], 'java': [ 'minecraft:light_gray_concrete' ] }, # custom_8
  { 'dungeons': [ 0xe9, 0b0000 ], 'java': [ 'minecraft:cyan_concrete' ] }, # custom_9
  { 'dungeons': [ 0xea, 0b0000 ], 'java': [ 'minecraft:blue_concrete' ] }, # custom_10
  { 'dungeons': [ 0xeb, 0b0000 ], 'java': [ 'minecraft:purple_concrete' ] }, # custom_11
  { 'dungeons': [ 0xec, 0b0000 ], 'java': [ 'minecraft:brown_concrete' ] }, # custom_12
  { 'dungeons': [ 0xed, 0b0000 ], 'java': [ 'minecraft:green_concrete' ] }, # custom_13
  { 'dungeons': [ 0xee, 0b0000 ], 'java': [ 'minecraft:red_concrete' ] }, # custom_14
  { 'dungeons': [ 0xef, 0b0000 ], 'java': [ 'minecraft:black_concrete' ] }, # custom_15
  { 'dungeons': [ 0xf3, 0b0000 ], 'java': [ 'minecraft:mycelium' ] },
  { 'dungeons': [ 0xf5, 0b0000 ], 'java': [ 'minecraft:stonecutter' ] },
  { 'dungeons': [ 0xfb, 0b0000 ], 'java': [ 'minecraft:observer', { 'facing': 'down', 'powered': 'false' } ] },
  { 'dungeons': [ 0xfb, 0b0001 ], 'java': [ 'minecraft:observer', { 'facing': 'up', 'powered': 'false' } ] },
  { 'dungeons': [ 0xfb, 0b0010 ], 'java': [ 'minecraft:observer', { 'facing': 'north', 'powered': 'false' } ] },
  { 'dungeons': [ 0xfb, 0b0011 ], 'java': [ 'minecraft:observer', { 'facing': 'south', 'powered': 'false' } ] },
  { 'dungeons': [ 0xfb, 0b0100 ], 'java': [ 'minecraft:observer', { 'facing': 'west', 'powered': 'false' } ] },
  { 'dungeons': [ 0xfb, 0b0101 ], 'java': [ 'minecraft:observer', { 'facing': 'east', 'powered': 'false' } ] },
  { 'dungeons': [ 0xfb, 0b1000 ], 'java': [ 'minecraft:observer', { 'facing': 'down', 'powered': 'true' } ] },
  { 'dungeons': [ 0xfb, 0b1001 ], 'java': [ 'minecraft:observer', { 'facing': 'up', 'powered': 'true' } ] },
  { 'dungeons': [ 0xfb, 0b1010 ], 'java': [ 'minecraft:observer', { 'facing': 'north', 'powered': 'true' } ] },
  { 'dungeons': [ 0xfb, 0b1011 ], 'java': [ 'minecraft:observer', { 'facing': 'south', 'powered': 'true' } ] },
  { 'dungeons': [ 0xfb, 0b1100 ], 'java': [ 'minecraft:observer', { 'facing': 'west', 'powered': 'true' } ] },
  { 'dungeons': [ 0xfb, 0b1101 ], 'java': [ 'minecraft:observer', { 'facing': 'east', 'powered': 'true' } ] }

]

blocks_by_java_id = {}
blocks_by_dungeons_id = {}

for i, b in enumerate(blocks):
  if b['java'][0] in blocks_by_java_id:
    blocks_by_java_id[b['java'][0]].append(b)
  else:
    blocks_by_java_id[b['java'][0]] = [b]

  if len(b['dungeons']) > 1:
    if len(b['dungeons']) > 2:
      for m in range(16):
        if m & b['dungeons'][2] == b['dungeons'][1]:
          blocks_by_dungeons_id[b['dungeons'][0] << 4 | m] = b
    else:
      blocks_by_dungeons_id[b['dungeons'][0] << 4 | b['dungeons'][1]] = b
  else:
    for m in range(16):
      blocks_by_dungeons_id[b['dungeons'][0] << 4 | m] = b

def find_java_block(block):
  namespaced_id = block.namespace + ':' + block.id
  if not namespaced_id in blocks_by_java_id:
    return None

  if len(block.properties) > 0:
    for b in blocks_by_java_id[namespaced_id]:
      if len(b['java']) > 1:
        matches = True
        for prop in b['java'][1]:
          if b['java'][1][prop] != block.properties[prop].value:
            matches = False
            break
        if matches:
          return b
      else:
        return b
  else:
    return blocks_by_java_id[namespaced_id][0]

  return None

def find_dungeons_block(block_id, block_data=0):
  k = block_id << 4 | block_data
  if k in blocks_by_dungeons_id:
    return blocks_by_dungeons_id[k]
  else:
    return None